looker-open-source/sdk-codegen

fetchSpec.ts
since most Looker instances do not require auth to read the API spec
A minor point perhaps, but this change enables running `yarn generate` without requiring that credentials be set up in the .ini first.  Shortens time to first output for some users.
=> Update fetchSpec to first try without auth

sdkGenerator.spec.ts, sdkGenerator.ts, sdkModels.ts, tsconfig.json, tslint.json
prototype WIP.  Next step: type resolution
=> TS driven generator classes with internal templating

python/looker/rtl/user_session.py
A few changes to `user_session.py` following Joel's feedback as well as some refactoring due to other RTL changes
=> Improve UserSession

python/Pipfile, python/Pipfile.lock, python/looker/rtl/api_methods.py, python/looker/rtl/api_settings.py, python/looker/rtl/auth_token.py, python/looker/rtl/requests_transport.py, python/looker/rtl/serialize.py, python/looker/rtl/transport.py, python/looker/rtl/user_session.py
- minor formatting changes in line with the google style guide
- added pytest-cov as a test coverage library as a dev dependency
=> Fix issue with cattr not structuring from config file properly

python/Pipfile, python/Pipfile.lock, python/looker/rtl/api_methods.py, python/looker/rtl/api_settings.py, python/looker/rtl/serialize.py, python/looker/rtl/user_session.py, python/mypy.ini, python/tests/rtl/test_serialize.py, python/tests/rtl/test_user_session.py
APIMethods and serialize fixes
=> Python RTL updates

python.fmt.spec.ts, python.fmt.ts
- handle mapping reserved python words
- cattr can't handle `ForwardRef()` types
- all sdk model fields and method "in query" args are Optional[] = None
=> Python formatter updates

python.fmt.ts, python/looker/rtl/api_methods.py
This allows mypy to do proper checking.
=> Move APIMethods.configure down to LookerSDK

python.fmt.ts, python/looker_sdk/client.py, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/transport.py, python/looker_sdk/rtl/user_session.py, python/tests/integration/test_methods.py, python/tests/rtl/test_user_session.py
TODOs:
1. Refactor `UserSession` to be more dry.
2. Experiment with the magic methods needed in methods.py. Potentially make them available in client.py instead.
3. Write tests for `UserSession`
=> WIP: modify user_session to handle sudoing

python/looker_sdk/rtl/api_settings.py, python/tests/integration/test_methods.py, python/tests/rtl/test_api_settings.py, src/python.gen.ts
- Now supporting verify_ssl through the env variable ENV_VERIFY_SSL
- Removed the line comments from the generated models
=> Some more tweaks

python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/model.py, python/tests/integration/test_methods.py, python/tests/rtl/test_api_methods.py, src/python.gen.ts
This handles the "CSV" collection format
=> Python: implement DelimSequence

Pipfile.lock, src/codeGen.ts, src/convert.ts, src/fetchSpec.spec.ts, src/fetchSpec.ts, src/legacy.ts, src/python.gen.ts, src/sdkConfig.ts, src/sdkModels.ts, src/typescript.gen.ts, src/utils.ts, typescript/looker/README.md, typescript/looker/index.ts, typescript/looker/package.json, typescript/looker/rtl/apiSettings.ts, typescript/looker/rtl/browserTransport.ts, typescript/looker/rtl/constants.spec.ts, typescript/looker/rtl/constants.ts, typescript/looker/rtl/nodeSdk.ts, typescript/looker/rtl/nodeSession.spec.ts, typescript/looker/rtl/nodeSession.ts, typescript/looker/rtl/nodeSettings.spec.ts, typescript/looker/rtl/nodeSettings.ts, typescript/looker/rtl/nodeTransport.ts, typescript/looker/rtl/transport.ts, typescript/looker/test/methods.spec.ts, typescript/looker/yarn.lock
Also got the BrowserSDK closer, but it still will not work
=> Fixed for node environment variable usage for config

python/Pipfile, python/Pipfile.lock, python/tests/integration/test_methods.py
Test showing three different render outputs for running a look
=> Added a python test for running looks in csv, json, and json_label format

python/looker_sdk/rtl/requests_transport.py, python/tests/integration/test_methods.py, python/tests/rtl/test_requests_transport.py
=> use x-looker-appid for user agent tag

python/looker_sdk/rtl/api_settings.py, python/tests/integration/test_methods.py, python/tests/rtl/test_api_settings.py
=> Python SDK: Allow quoted string config vars

kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/main/com/looker/rtl/UserSession.kt
=> Pass UserSession login credentials in body instead of query params

kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/main/com/looker/rtl/UserSession.kt
=> Increasing unquoting of configuration variables

swift/looker/rtl/authSession.swift
=> Pass API credentials in body rather than query for auth session

python/tests/conftest.py, python/tests/integration/test_methods.py, test/data.yml
- Added a test that creates a test look using data.yml
- A fixture that deletes the test look before the crud tests run
=> Python SDK: crud tests for looks

python/Pipfile, python/Pipfile.lock, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/api_settings.py, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_session.py, python/tests/rtl/test_requests_transport.py, src/python.gen.ts
=> Python SDK: Better support for custom configuration readers

typescript/looker/rtl/nodeTransport.ts
Broke this back in Sept, fixing it now
=> Avoid converting binary downloads to UTF-8

python/tests/conftest.py, python/tests/integration/test_methods.py, test/data.yml
To run:
docker-compose build base; docker-compose build python
docker-compose run python
=> Fixed tests to not use thelook

kotlin/src/main/com/looker/sdk/3.1/models.kt, kotlin/src/main/com/looker/sdk/4.0/models.kt, kotlin/src/test/TestAsync.kt, kotlin/src/test/TestMethods.kt, src/kotlin.gen.ts, swift/looker/rtl/baseTransport.swift
Added `: Serializable` to Kotlin SDK models
=> Kotlin models are now serializable

src/sdkModels.spec.ts, src/sdkModels.ts
To facilitate reusable filtered results that match the shape of the taglist and typelist in the model for categorical display in a UI
=> Some refinements to search results

swift/looker/rtl/baseTransport.swift
This should handle more failure conditions mo bettah
=> Improved error handling for Swift HTTP requests

kotlin/src/main/com/looker/sdk/3.1/models.kt, kotlin/src/main/com/looker/sdk/4.0/models.kt, python/looker_sdk/sdk/api31/models.py, python/looker_sdk/sdk/api40/models.py, swift/looker/sdk/models.swift, typescript/looker/sdk/3.1/models.ts, typescript/looker/sdk/4.0/models.ts
Includes re-adding folder_id for 3.1
=> Regenerate sdks for 7.6

kotlin/src/main/com/looker/rtl/OAuthSession.kt, kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/test/TestMethods.kt, yarn.lock
SDK errors now report the operation that failed and uniformly throw a `java.lang.Error` exception.
- test added
- linty freshness
=> Improved error handling for Kotlin transport

python/README.rst
=> Update python README to clarify version support

packages/api-explorer/package.json, packages/api-explorer/src/components/TryIt/components/ShowResponse.tsx, packages/api-explorer/src/reducers/spec/utils.ts, packages/api-explorer/tsconfig.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-scripts/src/testUtils/testUtils.ts, packages/sdk-codegen/src/sdkModels.ts, packages/sdk-codegen/src/testUtils/testUtils.ts, packages/sdk/package.json, yarn.lock
Fixes:
- `yarn build`
- `yarn develop`
Node infection in sdkModels.ts
=> Fixing multiple api-explorer build issues

packages/sdk-codegen-scripts/src/fetchSpec.spec.ts, packages/sdk-codegen-scripts/src/fetchSpec.ts, packages/sdk-codegen/src/swift.gen.spec.ts, packages/sdk/src/rtl/nodeTransport.spec.ts, packages/sdk/src/test/methods.spec.ts, yarn.lock
- also fixed LookerVersion retrieval
=> Fixed some broken tests

kotlin/build.gradle, kotlin/gradle/wrapper/gradle-wrapper.properties
- Use `gradle test` to run the Kotlin SDK tests
- Updated Gradle to 6.5.1
=> Kotlin gradle default action only builds jar

packages/api-explorer/src/components/DocMethodSummary/DocMethodSummary.tsx, packages/api-explorer/src/components/DocMethodSummary/utils.tsx, packages/api-explorer/src/components/ExplorerStyle/ExplorerStyle.tsx, packages/api-explorer/src/components/ExplorerStyle/index.ts, packages/api-explorer/src/components/Search/Search.tsx, packages/api-explorer/src/components/index.ts, packages/api-explorer/src/reducers/search/reducer.ts, packages/api-explorer/src/scenes/TagScene/TagScene.spec.tsx, packages/api-explorer/src/scenes/TagScene/TagScene.tsx, packages/api-explorer/src/scenes/TagScene/utils.ts, packages/sdk-codegen/src/sdkModels.ts
=> Api Explorer: Tag Scene filter UI behavior

kotlin/src/main/com/looker/rtl/OAuthSession.kt
Per request by the mobile team
=> Very small tweak to OAuthSession.kt getToken

packages/run-it/src/components/ConfigForm/ConfigDialog.tsx, packages/run-it/src/components/ConfigForm/ConfigForm.tsx, packages/run-it/src/components/ConfigForm/configUtils.ts, packages/run-it/src/components/RequestForm/RequestForm.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx
- Fixed issue with DialogForm url validation
- Added ability to clear RequestForm inputs
=> Added request form input persistence

packages/run-it/src/components/ConfigForm/ConfigForm.spec.tsx, packages/run-it/src/components/ConfigForm/ConfigForm.tsx
- removed the radio group toggle for choosing between session and local storage
- config is always saved to local storage
=> Making server url configuration always go to local storage

packages/sdk-codegen/src/swift.gen.ts, swift/looker/sdk/methods.swift, swift/looker/sdk/models.swift
also removed `required` from the reserved word list since the Swift compiler warns about it
=> Made swift streams publicly lazy

examples/python/Pipfile, examples/python/Pipfile.lock, examples/python/query_task.py, python/CHANGELOG.md, python/CHANGES.txt, python/README.rst, python/setup.py
Started a changelog beginning with the newest release and updated the
readme.
=> Python changelog and 0.1.3b16 release

swift/looker/Tests/lookerTests/authSessionTests.swift, swift/looker/Tests/lookerTests/methodsTests.swift, swift/looker/rtl/authSession.swift, swift/looker/rtl/constants.swift, swift/looker/rtl/transport.swift
- See testMe() for sample working code
- Made Constants for various version variables public
=> Swift SDK: Added setToken top-level function for AuthSession

bin/smoke, package.json, packages/api-explorer/package.json, packages/extension-api-explorer/package.json, packages/run-it/package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-utils/package.json, packages/sdk-codegen/package.json, packages/sdk-codegen/src/csharp.gen.spec.ts, packages/sdk-rtl/package.json, packages/sdk/package.json
Had to skip a C# generator test for now so I could publish.
Also had to explicitly add the publish scope of `public` for every package to be published. I guess that's a new requirement.
=> Changes to publish latest Typescript SDK

package.json, packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/components/DocMarkdown/DocMarkdown.tsx, packages/api-explorer/src/components/NotFound/NotFound.tsx, packages/api-explorer/src/components/NotFound/index.ts, packages/api-explorer/src/reducers/index.ts, packages/api-explorer/src/reducers/spec/index.ts, packages/api-explorer/src/reducers/spec/utils.spec.ts, packages/api-explorer/src/reducers/spec/utils.ts, packages/api-explorer/src/routes/AppRouter.tsx, packages/api-explorer/src/routes/index.ts, packages/api-explorer/src/routes/utils.spec.tsx, packages/api-explorer/src/routes/utils.tsx, packages/api-explorer/src/scenes/TagScene/TagScene.tsx, packages/api-explorer/src/test-data/specs.ts
Added a `validateAndRender` method for validating route params before rendering a scene.
=> Route Param Validation

examples/ruby/README.md, examples/ruby/create_themes.rb
Adding an example to create themes in Looker instance using Ruby SDK
=> ruby example to create themes

packages/hackathon/package.json, packages/hackathon/src/Hackathon.tsx, packages/hackathon/src/components/Header/Header.tsx, packages/hackathon/src/components/Header/index.ts, packages/hackathon/src/components/Loading/Loading.tsx, packages/hackathon/src/components/Loading/index.ts, packages/hackathon/src/components/SideNav/SideNav.tsx, packages/hackathon/src/components/SideNav/index.ts, packages/hackathon/src/components/index.ts, packages/hackathon/src/reducers/projects/store.ts, packages/hackathon/src/routes/AppRouter.tsx, packages/hackathon/src/routes/index.ts, packages/hackathon/src/scenes/AdminScene/AdminScene.tsx, packages/hackathon/src/scenes/AdminScene/index.ts, packages/hackathon/src/scenes/HomeScene/HomeScene.tsx, packages/hackathon/src/scenes/JudgingScene/JudgingScene.tsx, packages/hackathon/src/scenes/JudgingScene/index.ts, packages/hackathon/src/scenes/NotFoundScene/NotFoundScene.tsx, packages/hackathon/src/scenes/NotFoundScene/index.ts, packages/hackathon/src/scenes/ProjectsScene/ProjectsScene.tsx, packages/hackathon/src/scenes/UsersScene/UsersScene.tsx, packages/hackathon/src/scenes/UsersScene/index.ts, yarn.lock
=> Restructured and added routing

examples/python/Pipfile, examples/python/Pipfile.lock, python/CHANGELOG.md, python/setup.py
=> Python SDK: deploy version 0.1.3b18

README.md, packages/sdk-codegen/README.md
Out with the old, in with the new
Minor cleanup to give a better overview of the repository
=> Clean up the main README

packages/sdk-codegen/src/codeGen.ts, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts, packages/sdk-codegen/src/typescript.gen.spec.ts, packages/sdk-codegen/src/typescript.gen.ts
Implemented python calling syntax generation. Also modified style of
typescript call syntax
=> Python makeTheCall

bin/unit_test, packages/sdk/test/methods.spec.ts
- created `bin/unit_test` script to run as part of and before `bin/smoke`
- `bin/unit_test typescript` runs the `packages/sdk-rtl` tests
- `bin/smoke typescript` runs the unit tests and the `packages/sdk/test` tests
- JUnit XML-formatted results are named `results/ts_sdk_unit.xml` and `results/ts_sdk_smoke.xml`
=> Completed smoke test pattern tests for TS SDK

kotlin/gradle.properties, kotlin/src/main/com/looker/rtl/Transport.kt
This is a prerequisite for using kotlinx.serialization with the ktor
client, so time to upgrade before we experiment with that.
=> Upgrade to ktor 1.4.2

.github/workflows/python-ci.yml, babel.config.js, examples/typescript/downloadTile.ts, package.json, packages/api-explorer/src/components/DocSdkUsage/DocExamples.tsx, packages/api-explorer/src/context/examples/LodeContext.ts, packages/sdk-codegen-scripts/scripts/mineExamples.ts, packages/sdk-codegen-scripts/src/declarationMiner.ts, packages/sdk-codegen-scripts/src/exampleMiner.spec.ts, packages/sdk-codegen-scripts/src/exampleMiner.ts, packages/sdk-codegen/src/declarationInfo.ts, packages/sdk-codegen/src/exampleInfo.spec.ts, packages/sdk-codegen/src/exampleInfo.ts, packages/sdk-codegen/src/specDiff.spec.ts, packages/sdk-codegen/src/typescript.gen.ts, packages/sdk-rtl/package.json, packages/sdk/CHANGELOG.md, packages/sdk/README.md, packages/sdk/package.json, packages/sdk/src/3.1/methods.ts, packages/sdk/src/4.0/methods.ts, packages/sdk/src/extensionSdk.ts, packages/sdk/test/methods.spec.ts, yarn.lock
Adds modules for Typescript SDKs. If the canary build works, I'll publish the update.
=> Creating modules for sdk packages

go/example/main.go, go/rtl/auth.go
Adds one more golang example that gets all the LookML projects.
This example would have failed with this panic before this change.
`panic: reflect: call of reflect.Value.IsNil on string Value`
=> Fixes issue with default arguments in golang

.env, .github/workflows/tssdk-ci.yml, .gitignore, package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-scripts/src/sdkConfig.ts, packages/sdk-rtl/package.json, packages/sdk-rtl/src/apiSettings.ts, packages/sdk-rtl/src/nodeServices.ts, packages/sdk-rtl/src/nodeSession.spec.ts, packages/sdk-rtl/src/nodeSettings.spec.ts, packages/sdk-rtl/src/nodeSettings.ts, packages/sdk-rtl/src/testUtils/testUtils.ts, packages/sdk/test/methods.spec.ts, yarn.lock
First draft of CI for TS SDK
This is currently a draft PR
=> WIP Github actions for TS SDK CI/CD

python/README.rst, python/python-sdk-tutorial.ipynb
Including a full tutorial .ipynb in the python directory and adding an "Open in Colab" button to the README for easy discovery and usage. 
If you've got comments on the colab tutorial itself, probably easiest to comment on the internal version that's shared with you. 
I also made a couple loosie tweaks to the quickstart to add clarity in a couple tiny areas.
=> Python SDK colab tutorial

python/CHANGELOG.md, python/Pipfile, python/Pipfile.lock, python/setup.py
https://github.com/Tinche/cattrs/issues/119
=> fix(python): pin cattrs at 1.1.2

.github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml, packages/api-explorer/package.json, packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/components/DocSdkUsage/DocExamples.tsx, packages/extension-api-explorer/bin/deploy, packages/extension-api-explorer/package.json, packages/hackathon/package.json, packages/hackathon/src/scenes/ResourceScene/resource_data.ts, packages/run-it/package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-utils/package.json, packages/sdk-codegen/package.json, packages/sdk-node/package.json, packages/sdk/package.json, packages/wholly-sheet/package.json, python/README.rst, python/python-sdk-tutorial.ipynb, swift/looker/README.md
Updated all primary branch references to be `main`
- `$default-branch` does not work as documented in GitHub workflow
=> Pulling the main switch

packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-scripts/src/legacyGenerator.ts, yarn.lock
This only affects the `legacy` generator
=> Upgraded openapi-generator-cli for axios security issue

docs/cors.md, kotlin/README.md, packages/sdk-node/README.md, packages/sdk/README.md, swift/looker/README.md
Updated:
- Typescript Browser SDK readme
- Typescript Node SDK readme
- Kotlin SDK readme
- Swift SDK readme
=> Minor improvements to some SDK readmes

packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/components/Header/ApiSpecSelector.spec.tsx, packages/api-explorer/src/components/Header/ApiSpecSelector.tsx, packages/api-explorer/src/components/Header/Header.tsx, packages/api-explorer/src/components/SideNav/SideNav.tsx, packages/api-explorer/src/reducers/spec/utils.spec.ts, packages/api-explorer/src/reducers/spec/utils.ts
=> Spec selection is a little cleaner

.github/pull_request_template.md, CONTRIBUTING.md, package.json
- added pull_request_template.md
- removed `bootstrap` from package.json
Suggestions for refining the checklist are welcome.
=> chore: Created CONTRIBUTING.md

.github/pull_request_template.md, CONTRIBUTING.md
update CONTRIBUTING.md and the PR template
=> chore: Updated the contributing checklist

.github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
image already pushed to artifact repository and secrets added to GH
=> ci: enable looker 21_4

.github/workflows/python-release.yml
=> chore: add a workflow_dispatch to python-release

.release-please-manifest.json, release-please-config.json
=> chore: release-please config/manifest

release-please-config.json
trying out bump-minor-pre-major option to see if that coerces
a "feat" commit on a pre-major package to bump the patch instead
of the minor as minor bumps are considered breaking in pre-major
packages
=> chore: release-please config fine tuning

packages/sdk/package.json
=> chore: clean up unused package dev dependencies

packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-scripts/src/convert.spec.ts, packages/sdk-codegen/package.json, packages/sdk-codegen/src/specConverter.ts, packages/sdk-codegen/src/testUtils/testUtils.ts
Moved some files around and removed `@looker/sdk` and `@looker/sdk-node` dependencies from `sdk-codegen`
=> chore: clean up codegen dependencies

packages/sdk-codegen/src/python.gen.spec.ts
=> chore: fix codegen python test

python/README.rst
Fix Python SDK README
Fixes #561 https://github.com/looker-open-source/sdk-codegen/issues/561 🦕
=> docs: Fixed missing quote in Python SDK README example

packages/api-explorer/src/components/DocCode/DocCode.tsx, packages/sdk-codegen/src/codeGenerators.ts
=> fix(ApiExplorer): Added support for Golang syntax highlighting

.github/workflows/release-metrics.yml
=> chore: fix release-metrics workflow yml

packages/api-explorer/src/components/SideNav/SideNavMethods.spec.tsx, packages/api-explorer/src/components/SideNav/SideNavTypes.spec.tsx, packages/api-explorer/src/scenes/TagScene/TagScene.spec.tsx
=> chore(ApiExplorer): Fixed broken tests

release-please-config.json
to fix https://github.com/looker-open-source/sdk-codegen/pull/584
=> chore: extension-api-explorer release-as 21.4.1

packages/extension-api-explorer/package.json, packages/extension-api-explorer/src/ExtensionApiExplorer.tsx, packages/extension-api-explorer/src/Loader.tsx, yarn.lock
=> feat: prettier loading scene while fetching specs

packages/sdk-rtl/src/oauthSession.spec.ts
Typescript OAuth test got broken on main probably due to dependency update
=> fix: Typescript OAuth test

package.json
Two additional lint scripts to run against modified files. One script reports, the other attempts to fix.
=> chore: additional package.json lint scripts

examplesIndex.json, packages/sdk-codegen-scripts/src/exampleMiner.spec.ts
With the removal of the python hackathon app, we need to update the mined examples index and a test for the number of examples found
=> chore: updated mined examples

release-please-config.json
temporarily set changelog-sections on packages/sdk to work around
c7b5bf81 which should have been a 'fix:' commit
=> chore: release-please set versions

packages/extension-sdk/src/connect/connect_extension_host.spec.ts
📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally, it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before …
=> chore: fix broken test

jest.config.js, packages/api-explorer/src/utils/envAdaptor.spec.ts, packages/api-explorer/src/utils/envAdaptor.ts, packages/api-explorer/src/utils/index.ts, packages/extension-api-explorer/src/utils.spec.ts, packages/extension-api-explorer/src/utils.ts
Also centralizes setting of theme
=> fix: font color when API Explorer is embedded

package.json, packages/api-explorer/package.json, packages/api-explorer/webpack.dev.config.js, packages/extension-api-explorer/package.json, packages/extension-api-explorer/webpack.dev.config.js, packages/extension-api-explorer/webpack.prod.config.js, packages/hackathon/package.json, packages/hackathon/webpack.dev.config.js, packages/hackathon/webpack.prod.config.js, packages/run-it/package.json, webpack.browser.config.js, yarn.lock
Add analyze scripts to standalone api explorer, extension api explorer and hackathon extension
=> chore: Upgrade webpack to version 5.

packages/api-explorer/src/components/DocSDKs/DocSDKs.tsx
=> fix: rerender declarations on type/method change

packages/api-explorer/package.json, packages/api-explorer/src/components/DocMarkdown/common.tsx, packages/code-editor/package.json, packages/run-it/package.json, yarn.lock
📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally, it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before …
=> fix: sync design-tokens/icons dependency constraint

.github/workflows/apix-ci.yml, .github/workflows/tssdk-ci.yml
=> ci: created API Explorer workflow

packages/sdk-node/README.md, packages/sdk-rtl/README.md, packages/sdk/README.md, python/README.rst
=> docs: Typescript and Python README updates for GA

examples/python/README.md, examples/python/add_contents_to_favorite.py, examples/python/transfer_all_schedules.py
Hi team, as part of the DCL reduce contact rate effort, I am submitting two new examples using Python. I'd appreciate your comment and review so I can improve my future code snippets. Thank you
- add_contents_to_favorite.py: add a specific Board or Dashboard to "Favorites" for a list of users 
- transfer_all_schedules.py: transfer all of schedules of foo@looker.com to bar@looker.com 
- add the two scripts and reorder the section in README for the python example folder for better navigation. 
Tagging @joeldodge79, @josephaxisa per Xin's instruction. 
Thank you!
=> feat(New Python Examples): Adding 2 new Python examples

release-please-config.json
- alphabetize for easier comparison with .release-please-manifest.json
- inline package definitions for easer GitHub PR diff viewing
- hardcode some versions for next release
=> chore: release-please config tweaks

packages/sdk/src/index.ts
Improve the import pattern for the functional SDK
=> fix: export funcs for TS SDK

packages/sdk-rtl/src/paging.ts
Minor code comment change to clarify the `sdk` parameter
=> fix: explain pager and pageAll sdk param better

packages/sdk-node/src/nodeTransport.ts, packages/sdk-rtl/src/browserTransport.ts
Also improved error handling for both browser and node transports
=> fix: browserTransport.ts retains ok: false now

packages/api-explorer/src/ApiExplorer.tsx
This change allows an entity other than APIX explorer to hide/show the APIX sidebar.
The dev portal navigation bar is independent of the APIX nav bar. A previous change, allowed the APIX nav bar to be hidden when APIX is running in the dev portal. The issue with that change  was that the toggle to open/close the sidebar was no longer visible and the toggle in the dev portal had no way to communicate with the APIX explorer so that it could hide/show the side bar. This change adds a window message listener to APIXExplorer when it operates in headless mode. When the window message is received it toggles the sidebar visibility.
=> feat: apix sidebar toggle for dev portal

.gitignore, README.md, shell.nix
Also trivial tweak to the README.md
=> chore: update nix config

packages/api-explorer/package.json, packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/components/SideNav/SideNav.tsx
This PR gets rid of the triple scroll bar in dev portal and adds the label
=> fix: dev portal apix tweaks

packages/api-explorer/src/components/SideNav/SideNav.tsx
As per Chris' suggestion
https://github.com/llooker/developer-portal/pull/43#issuecomment-883550714
=> fix: uses consistent heading text

examplesIndex.json
Is anything else required for this change?
=> chore: update examples index

release-please-config.json
removing special handling for sdk-codegen* packages
=> chore: release-please config

.github/workflows/release-please.yml, release-please-config.json
this should cause release-please to go back to
e4c24ed0af4c70ce02eb910a367a306acb9578e7 (release pr #750)
for the last release bypassing the reverted release pr (#759)
=> ci: release-please bugfix

packages/hackathon/README.md, packages/hackathon/src/scenes/HomeScene/agenda.ts
Screenshot: https://screenshot.googleplex.com/BKz4dhbhYMoEnFa.png
Fixing: b/200085421
=> feat: Add JPN agenda.ts and add yarn command in readme.md for hackathon app

packages/hackathon/src/scenes/HomeScene/HomeScene.tsx, packages/hackathon/src/scenes/HomeScene/agenda.ts
=> chore: localize agenda to JPN HackApp

packages/hackathon/src/data/projects/sagas.ts, packages/hackathon/src/scenes/ResourceScene/resource_data.ts
- Defaulted new project judging consent to true
=> fix: Updated hackathon resources and project description

packages/extension-sdk/README.md
1. Use async/await example
2. Fix links
=> docs: Update extension-sdk README

.github/workflows/resources-ci.yml
Added CI that triggers on resources index code changes and resource json
changes. It will test/analyze/build the resources index and also check
if resources.json or resource-lock.json are missing changes.
I've tested this locally with act. https://github.com/nektos/act
=> chore: Added resources index CI

.github/workflows/go-ci.yml, .github/workflows/required-checks-hack-ci.yml
Smoke test to come soon after adding environment variable support to Go SDK.
=> feat: Added unit test CI for Go SDK

packages/extension-playground/package.json, yarn.lock
we had a stale version in a package dependency
=> fix: clean up package dependencies

.github/workflows/go-ci.yml, go/integration/integration_test.go
Added initial go integration tests and setup github actions for go integration tests.
Github actions based off python CI.
=> feat: Go SDK integration tests

package.json, yarn.lock
=> fix: url-parse dependabot issue

release-please-config.json
The 22.4 API update: https://github.com/looker-open-source/sdk-codegen/pull/1024
=> chore: update release-please config for 22.4

release-please-config.json
for https://github.com/looker-open-source/sdk-codegen/pull/1047 when it lands
=> chore: Update release-please-config.json

packages/extension-api-explorer/package.json, packages/extension-playground/package.json, yarn.lock
Needed up update package refs for API Explorer extension
=> fix: package refs for API Explorer extension

.github/workflows/tssdk-ci.yml, release-please-config.json
- also change TS SDK workflow to use node 14, 16, and 18
=> chore: reset release config CalVer

release-please-config.json
=> chore: fix ts sdk version for deployment

packages/api-explorer/e2e/diffScene.spec.ts, packages/api-explorer/e2e/e2e.spec.ts, packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/components/Header/Header.spec.tsx, packages/api-explorer/src/components/SelectorContainer/SelectorContainer.spec.tsx, packages/api-explorer/src/components/SelectorContainer/SelectorContainer.tsx, packages/api-explorer/src/routes/AppRouter.tsx, packages/api-explorer/src/scenes/DiffScene/DiffScene.tsx, yarn.lock
from `/diff/:specKey/:compareSpecKey` to `/:specKey/diff/:compareSpecKey `in order for it to follow the same pattern as all other routes
=> feat: change diff scene route

jest.config.js, packages/api-explorer/package.json, packages/code-editor/package.json, packages/extension-api-explorer/package.json, packages/extension-playground/package.json, packages/extension-utils/package.json, packages/hackathon/package.json, packages/run-it/package.json, packages/run-it/src/components/RequestForm/RequestForm.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx, yarn.lock
Remove deprecated `@looker/components-date` dependency
=> chore: update @looker/components and @looker/design-tokens

python/looker_sdk/error.py, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/auth_session.py, python/tests/integration/test_methods.py
* fix response handling when response payload is empty (e.g. 204)
* add error detail handling for Python SDK
=> fix: add error detail handling for Python SDK

.github/workflows/python-ci.yml
=> chore: disable all python integration tests

LICENSE, package.json, packages/embed-services/LICENSE, packages/embed-services/package.json, packages/embed-services/src/index.ts, packages/embed-services/tsconfig.build.json
This is just a skeleton of the package that will contain the service layer for looker embed components.
=> chore: embed-services package

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/go-ci.yml, .github/workflows/hackathon-ci.yml, .github/workflows/lerna-publish.yml, .github/workflows/python-ci.yml, .github/workflows/python-publish.yml, .github/workflows/release-metrics.yml, .github/workflows/required-checks-hack-ci.yml, .github/workflows/resources-ci.yml, .github/workflows/tssdk-ci.yml
Fix deprecations in github actions
=> chore: fix deprecations

go/rtl/auth.go, go/rtl/auth_test.go
This change makes Go SDK set `Content-Type` header according to the body's type. Either `text/plain` if it is a string, or `application/json` if it is JSON formatted string. The oauth2 transport automatically sets a url encoded content type header for `login` call. This change will fix requests 500'ing on `%` being in the json formatted body. 
Fixes: https://github.com/looker-open-source/sdk-codegen/issues/1075
=> fix: Make Go SDK set correct content-type header

packages/sdk/README.md
And try to fix release versioning with this commit.
Release-As: 23.14.1
=> chore: Update Typescript SDK Readme

packages/sdk/README.md
And try to force the release version again.
Release-As: 23.14.1
=> chore: Update Typescript SDK README.md

kotlin/gradle.properties
=> chore(deps): Bump ktor from 1.5.4 to 1.6.7 for Kotlin rtl

package.json
Ensuring all workspaces are declared as workspaces.
=> Add bin/looker-resources-index to workspaces.

examples/python/cloud-function-content-cleanup-automation/README.md, examples/python/cloud-function-content-cleanup-automation/main.py, examples/python/content_validator_comparison.py, examples/python/create_db_connections.py, examples/python/download_dashboard_pdf.py, examples/python/download_look.py, examples/python/download_tile.py, examples/python/kill_queries.py, examples/python/logout_all_users.py, examples/python/manage_schedules.py, examples/python/run_look_with_filters.py, examples/python/test_connection.py
- changes import statements to `import models40 as models` for examples
- fixed comment formatting on a few files
=> updating examples - addresses PR #1345

.github/workflows/release-metrics.yml
Was using wrong key causing publish metrics to fail
=> chore: Update release-metrics.yml

examplesIndex.json
Updating the API Explorer sdk examples index for latest source code changes in the repository
=> update the SDK examples index

python/setup.py
Fixes https://github.com/looker-open-source/sdk-codegen/issues/1197
=> Filtering out `tests` from Python package

python/setup.py
Fixes https://github.com/looker-open-source/sdk-codegen/issues/1197
Copy of https://github.com/looker-open-source/sdk-codegen/pull/1416
=> chore: Filtering out `tests` from Python package (#1416)

kotlin/src/main/com/looker/rtl/AuthSession.kt
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally, it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)
Fixes #<issue_number_goes_here> 🦕
=> feat: Kotlin: make isAuthenticated func in AuthSession open for extension to allow custom / proxy AuthSession
