.gitignore, python/Pipfile, python/Pipfile.lock, python/looker/rtl/requests_transport.py, python/looker/rtl/transport.py, python/tests/rtl/test_requests_transport.py
This is just the beginning of an exploration into python3 typing for
the transport "interface". I found this PEP interesting:
https://www.python.org/dev/peps/pep-3119/#abcs-vs-interfaces
not sure if abc is really what we want but I'd rather not use
zope.interface (I think we should try to keep dependancies small).
I've added a "configure" method to the transport interface as a low cost
implementation of configuring dependancy injection.
TODO:
- determine if we use dataclasses versus attrs
- flesh out transport.py interface/types
- actually implement and test requests_transport.py
=> Start typing transport.py based on transport.ts

python/looker/rtl/api_methods.py, python/tests/conftest.py, python/tests/integration/test_methods.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_token.py, python/tests/rtl/test_model.py, python/tests/rtl/test_requests_transport.py, python/tests/rtl/test_user_session.py
There's also some formatting changes to the unit tests previously created.
TODOs:
- Divide the integration tests into multiple files so that fixtures are not setup/thorn down more often than needed. `get_test_data` is an example of this. Another solution is to change it to a session scoped fixture.
- mypy is complaining about typing issues in fixture `create_users`
- mypy is also complaining about untyped decorated functions (Example: `@pytest.fixture`). There's a flag to turn this off but I want to find a way to turn it off for a particular directory.
- We are hitting this https://github.com/yaml/pyyaml/issues/202 which has been solved in newer `pyyaml` versions but those versions don't seem to work properly with `pipenv`. I will investigate further.
=> Integration tests for generated methods.py

Pipfile, Pipfile.lock, convert.ts, python.fmt.ts, utils.ts
Format the generated code as cleanly as possible using black
- Uses pipenv to install/update black and run it
- slight refactor on utils.run - no need for async and custom error
=> Run black on python generated code

sdkModels.spec.ts, sdkModels.ts, typescript/looker/test/methods.spec.ts
Per the "Required Properties" section of
https://swagger.io/docs/specification/data-models/data-types/
we will inspect the Type.Schema.required list to determine if
a property is required
Refactored makeWriteableType to push more creation logic into
WriteType in order to be able to centralize the decision of
whether a property is required or not inside the Property class.
=> Codegen: set required attribute of Property

python/looker_sdk/looker-sample.ini, python/looker_sdk/rtl/api_settings.py, python/looker_sdk/rtl/transport.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_user_session.py
Allow users to pass LOOKER_BASE_URL, LOOKER_CLIENT_ID, LOOKER_CLIENT_SECRET and LOOKER_EMBED_SECRET as env variables.
If settings are defined in both the config file and env variables, then the latter will override the config file settings.
=> Read credentials from env variables

python/Pipfile.lock, python/looker_sdk/rtl/api_settings.py, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/looker_sdk/rtl/versions.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_session.py, python/tests/rtl/test_requests_transport.py, src/python.gen.ts, src/typescript.gen.ts, typescript/looker/rtl/apiSettings.spec.ts, typescript/looker/rtl/apiSettings.ts, typescript/looker/rtl/nodeSession.ts, typescript/looker/rtl/versions.ts
For the codegen this is currently almost an exact copy of the typescript
generator with variable names snake_cased for python style. Might be
worth abstracting those variables out into config and moving the method
implementation into the base class.
For the python rtl - added User-Agent header like "PY-SDK 3.1.6.19". We
might want to also consider the same prefixing strategy we plan for
environment variable config here as well. (e.g. we'd be "LOOKER-PY-SDK
3.1.6.19")
=> Python: stamp looker/api version for user-agent

python/looker_sdk/__init__.py, python/looker_sdk/client.py, python/looker_sdk/error.py, python/looker_sdk/rtl/__init__.py, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/api_settings.py, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/auth_token.py, python/looker_sdk/rtl/model.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/serialize.py, python/looker_sdk/rtl/transport.py, python/looker_sdk/rtl/versions.py, python/tests/rtl/test_api_methods.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_session.py, python/tests/rtl/test_auth_token.py, python/tests/rtl/test_requests_transport.py, python/tests/rtl/test_serialize.py
I thought I read somewhere it was ok to only have a `LICENSE.txt` file but I can't find that now. The [google style guide](http://google.github.io/styleguide/pyguide.html#382-modules) says every file should have it so here it is
=> python RTL add license

python/Pipfile, python/Pipfile.lock, python/README.rst, python/setup.py
Found a bug for folks who only use pip: they were getting cattrs=0.9.0
instead of the cattrs=1.0.0rc0. Adding the minimum requirement in
setup.py fixes this.
Also tweaked the "sample project setup" documentation to be more
accurate for installing python 3.7 via pyenv as well as making sure the
pipenv environment is created using the correct version of python.
=> Python update readme and setup requirements

python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/tests/rtl/test_requests_transport.py, src/python.gen.spec.ts, src/python.gen.ts
This will allow users to pass a `transport.TransportSettings` object to override defaults or provide new transport settings  for a given call.
For now I set the default connection timeout to an arbitrary 1800 seconds. Will change this to a more reasonable one later on. The read timeout is 180 seconds to mimic the TS implementation.
=> add a transport_options arg to generated methods

python/Pipfile, python/Pipfile.lock, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/model.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/serialize.py, python/looker_sdk/rtl/transport.py, python/tests/integration/test_methods.py, python/tests/rtl/test_api_methods.py, python/tests/rtl/test_auth_session.py, python/tests/rtl/test_requests_transport.py, python/tests/rtl/test_transport.py, src/python.gen.spec.ts, src/python.gen.ts
Modified the transport interface so that it always returns bytes as well
as whether the "response mode" is binary or string and finally the text
encoding if any. The caller then decides how to de-serialize the
response.
fixes:#56
=> Python: binary reponse handling

python/looker_sdk/rtl/requests_transport.py, python/tests/integration/test_netrc.py, python/tests/rtl/test_requests_transport.py
As per https://3.python-requests.org/user/quickstart/#custom-headers, the requests library overrides auth headers with credentials specified in netrc if the auth parameter is not specified when calling requests.
The fix for now (until we support netrc files), is a NullAuth class that prevents this from happening, effectively ignoring the presence of netrc files on the system.
Fixes #61
=> Python: fix for netrc creds overriding http auth headers

src/typescript.gen.spec.ts, src/typescript.gen.ts
explicitly setting a property to null (being "nullable") is different
from whether the presence of a property is required ("required").
=> typescript formatter: optional only if not required

Pipfile.lock, src/typescript.gen.spec.ts, src/typescript.gen.ts, typescript/looker/README.md, typescript/looker/package.json, typescript/looker/rtl/apiMethods.ts, typescript/looker/rtl/baseTransport.ts, typescript/looker/rtl/browserSession.ts, typescript/looker/rtl/browserTransport.ts, typescript/looker/rtl/nodeTransport.spec.ts, typescript/looker/rtl/nodeTransport.ts, typescript/looker/rtl/transport.ts
- authenticator callback now works
- requests can now be
- automatically relative to the base url (`/path` with no authenticator)
- automatically relative to the api url paths (`/path` *with* authenticator)
- direct requests (path starts with `http://` or `https://`)
This way, the `BrowserTransport` instance can be used for ALL browser requests with the added bonus of giving typed responses back.
e.g. to create a proxy server call to retrieve the auth token from the web server:
```typescript
const getProxyToken = async () => {
const token = await gSDK.ok(gSDK.authSession.transport.request<IAccessToken,IError>(
'GET',
'http://join.demo:8080/token'
))
return token.access_token
}
```
=> Bug fixes and enhancements for `BrowserTransport`

kotlin/src/main/com/looker/rtl/UserSession.kt, swift/looker/Tests/lookerTests/authSessionTests.swift, swift/looker/Tests/lookerTests/constantsTests.swift, swift/looker/rtl/apiConfig.swift, swift/looker/rtl/apiSettings.swift, swift/looker/rtl/authSession.swift, swift/looker/rtl/constants.swift, typescript/looker/package.json, typescript/looker/rtl/nodeSession.ts, typescript/looker/test/methods.spec.ts
Needed to use `/api/3.1/login` path for session managers rather than `/login`
Fixed for
- Typescript
- Swift
- Kotlin
The Python SDK was already correct
=> [EMBED-547] Fix Kubernetes (GCP) cert errors.

kotlin/src/main/com/looker/rtl/ApiSettings.kt, kotlin/src/main/com/looker/rtl/Constants.kt, kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/test/TestApiSettings.kt, kotlin/src/test/TestMethods.kt, kotlin/src/test/TestTransport.kt, kotlin/src/test/TestUserSession.kt
- Additional API configuration settings supported
- Transport support for `verify_ssl` and `timeout` still pending
- Closes #100, #104
=> Closing some quick Kotlin SDK issues

tsconfig.common.json, tsconfig.json, typescript/looker/tsconfig.json
Test failures were caused by tslint issues. When the tests were added, the tests were run from the typescript/looker directory and worked. This is because the tsconfig at root and in typescript/looker were different. This change makes an attempt at reconciling the differences. The format of the two tsconfig files are now similar so they can be compared side by side. Matching options are at the top, options with different values next, followed lastly by different options.
The options causing the test failures were:
"noUnusedLocals": true,
"noUnusedParameters": true,
These were not in the tsconfig in typescript/looker. Fixing not an option as this caused the typescript/looker build to fail. Also tried tslint disable but for some reason jest did not honour these. In the end removed those …
=> Fix typescript test failures when tests run from root directory

typescript/looker/package.json, typescript/looker/rtl/apiSettings.spec.ts, typescript/looker/rtl/apiSettings.ts, typescript/looker/rtl/constants.spec.ts, typescript/looker/rtl/constants.ts, typescript/looker/rtl/nodeSettings.ts
For unquoting configuration value parity with other SDKs
Closes #133
=> Unquotes all Typescript configuration values before initializing

bin/smoke, kotlin/src/test/TestApiSettings.kt, kotlin/src/test/Utils.kt
- also added language test switch options to `bin/smoke` along with a `-h` `--help` option
=> Added tests that show how to override ApiSettings.readConfig() for Kotlin

src/swift.gen.ts, swift/looker/Package.swift, swift/looker/README.md, swift/looker/Tests/lookerTests/modelsTests.swift, swift/looker/Tests/lookerTests/transportTests.swift, swift/looker/looker.xcodeproj/project.pbxproj, swift/looker/rtl/AnyCodable.swift, swift/looker/rtl/AnyDecodable.swift, swift/looker/rtl/AnyEncodable.swift, swift/looker/rtl/serializer.swift, swift/looker/sdk/methods.swift, swift/looker/sdk/models.swift
- Modified the Swift generator to use `AnyCodable` instead of `Variant?`
- Commented out all references to `Variant` in the Swift SDK for probable eventual removal
- Added a `serialize` function to produce JSON from an SDK object (the opposite of `deserialize`)
- Added a test called `testDictFromJson` that shows how `vis_config` values can be examined. There are probably better code patterns for this.
=> Switching to AnyCodable as a solution to Swift's severe lack of support for deserializing JSON values to Any

swift/looker/README.md, swift/looker/Tests/lookerTests/authSessionTests.swift, swift/looker/Tests/lookerTests/baseTransportTests.swift, swift/looker/Tests/lookerTests/methodsTests.swift, swift/looker/rtl/apiMethods.swift, swift/looker/rtl/constants.swift
- `sdk.ok()` now throws if an error is encountered
- created a `listGetter` test harness like the one for Kotlin
- updated `methodsTests.swift` to use `listGetter`
=> Implemented error handling by default for Swift

kotlin/src/main/com/looker/rtl/Constants.kt, python/looker_sdk/rtl/constants.py, python/tests/conftest.py, python/tests/rtl/test_transport.py, swift/looker/Tests/lookerTests/baseTransportTests.swift, swift/looker/Tests/lookerTests/constantsTests.swift, swift/looker/Tests/lookerTests/transportTests.swift, typescript/looker/rtl/transport.spec.ts
Using `test/data.yml` content type values for binary and string mode detection tests for Typescript, Swift, and Python
=> Content type detection for string and binary mime types

swift/looker/Tests/lookerTests/methodsTests.swift, swift/looker/rtl/baseTransport.swift, swift/looker/rtl/transport.swift
Low-level refactor to capture error details that propagate up into `try` ... handlers
=> HTTP error code tracking for Swift SDK errors

typescript/looker/rtl/apiMethods.spec.ts, typescript/looker/rtl/apiMethods.ts
…ion.
Prefix now does not happen if base_url is not set (as is the case for extension transport). Node and browser transports must set the base url.
=> This fix failure of SDK in extensions as path is prefixed by API version

typescript/looker/rtl/apiMethods.ts, typescript/looker/rtl/extensionSdk.ts
examples: 
ExtensionSDK.createClient(host)  -> constructs LookerAPI31, DefaultSettings
ExtensionSDK.createClient(host, LookerAPI31) -> constructs LookerAPI31, DefaultSettings
ExtensionSDK.createClient(host, LookerAPI40) -> constructs LookerAPI40, DefaultSettings
ExtensionSDK.createClient(host, LookerAPI40, mySpecialSettings) -> constructs LookerAPI40
=> Enable caller to select which LookerSDK is used by the ExtensionSDK

README.md, src/convert.spec.ts, src/convert.ts, src/fetchSpec.spec.ts, src/languages.ts, src/legacy.ts, typescript/looker/rtl/nodeSettings.spec.ts
- The API 4.0 specification is now used by default for `yarn legacy`
- fixed namespace parameter specifier for the OpenAPI generator
- `x-looker-nullable` is replaced with `nullable` in the converted OpenAPI spec files
- legacy now only generates C# by default because the other active languages are supported by our code generator
- updated readme with more instructions for the legacy generator
=> Improved the legacy code generator

swift/looker/rtl/baseTransport.swift
Currently, with a nil response from the server, iOS will just explode on the cast to HTTPUrlResponse. This handles it a little more gracefully.
=> Don't crash in iOS on nil response.

python/looker_sdk/__init__.py, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/api_settings.py, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/tests/rtl/test_api_methods.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_session.py, python/tests/rtl/test_requests_transport.py
Make the python ApiSettings conform to the other sdks: instance properties/members will be the properties declared on `PTransportSettings` and `readConfig` will produce a dictionary with keys corresponding to further settings that `AuthSession` needs
I also refactored AuthSession to remove references to "admin" and
substituted "user" with "sudo" and DRY'ed out some logout code there.
=> Python SDK: settings refactor

python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/auth_token.py, python/tests/rtl/test_auth_session.py
Added OAuth session whose `_login` method calls `/api/token` with a
`refresh_token` grant_type. This assumes that you've set `self.token` with
an access token that has a `refresh_token`. We've provided a convenience
function to do this: `redeem_auth_code` which takes a temporary code
you've been given (see below) and calls `/api/token` with an
`authorization_code` grant_type.
In order to get the temporary code you must ask the authorization server
for it which will usually require a login, a redirect to authorize the
access, and then a final redirect to the location you supplied in the
initial request with a `code` query string parameter. For Looker
authorization we've provided another convenience function:
`create_auth_code_request_url` which will construct a URL with the
appropriate …
=> Python OAuth session support

python/looker_sdk/rtl/auth_session.py
/api/login requires auth prior to 7.4
/api/x.y/login is the correct endpoint to use
fixes #217
=> Use correct /login endpoint

python/looker_sdk/rtl/api_settings.py, python/tests/rtl/test_api_settings.py, python/tests/rtl/test_auth_session.py
raise NotFoundFileError when specifying a config file that does not
exist (defaulting to "looker.ini" will not raise).
raise configparser.NoSectionError error for bad section
better docstring describing usage
fixes #218
=> Python: better config file handling

packages/sdk-codegen/src/kotlin.gen.spec.ts, packages/sdk-codegen/src/kotlin.gen.ts
One attribute to rule them all
=> Cleaner use of Kotlin's JsonProperty attribute

csharp/rtl.Tests/AuthTokenTests.cs, csharp/rtl/ApiSettings.cs, csharp/rtl/AuthToken.cs, kotlin/src/main/com/looker/rtl/AuthToken.kt, kotlin/src/test/TestAuthToken.kt, packages/sdk/src/rtl/authToken.spec.ts, packages/sdk/src/rtl/authToken.ts, python/looker_sdk/rtl/auth_token.py, python/tests/rtl/test_auth_token.py, swift/looker/Tests/lookerTests/authTokenTests.swift, swift/looker/rtl/authToken.swift
Applied 10 second lag time to all existing `AuthToken` implementations
- also fixed missing `looker.ini` crash bug for Look#'s `ApiSettings.ReadConfig()`
Closes #223
=> Implementing 10 second lag time expiration check

packages/sdk-codegen/src/sdkModels.spec.ts, packages/sdk-codegen/src/sdkModels.ts, packages/sdk/src/rtl/browserSession.spec.ts, packages/sdk/src/rtl/oauthSession.spec.ts
- added `IType.parentTypes: KeyList` for types referenced in an `IType` properties collection
- Also restored preserving methods in "natural order" for spec tags/categories
=> Track parent type for properties that are custom types

package.json, packages/api-explorer/package.json, packages/extension-api-explorer/package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-utils/package.json, packages/sdk-codegen/package.json, packages/sdk/package.json, packages/try-it/package.json
Added a "watch" script that runs Babel in watch mode for all packages for a more pleasant development experience. 
Unfortunately I couldn't find a good way to also run `tsc -b tsconfig.build.json` in parallel so type errors presented during development might be false positives. On the other hand this is not very important since types don't matter at runtime, the pre-commit hook will flag and prevent them from being checked in and so does `yarn build`.
Also, naming is hard and I was torn between `watch` and `build:watch` for this script. Let me know if you have a preference.
=> Lerna ES build watcher

packages/api-explorer/package.json, packages/api-explorer/scripts/refresh_specs.ts, packages/api-explorer/scripts/register.ts, packages/api-explorer/scripts/utils.ts, packages/api-explorer/specs/Looker.3.0.oas.json, packages/api-explorer/specs/Looker.3.1.oas.json, packages/api-explorer/specs/Looker.4.0.oas.json, packages/sdk-codegen-scripts/src/fetchSpec.ts, packages/sdk-codegen-scripts/src/legacyGenerator.ts
- run `yarn refresh` in packages/api-explorer
- Cleaned up some codegen script files
- Put APIX script utils in a separate file
- updated all 3 API specs for APIX bundling
If desired, we could pretty-print the JSON output when we write it to the spec folder but typically we wouldn't be looking at the fetched/converted file directly so I didn't bother, particularly when our IDEs can prettify if necessary
=> yarn refresh in packages/api-explorer updates to the latest API specs

package.json, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts, python/looker_sdk/rtl/model.py, python/looker_sdk/sdk/api31/models.py, python/looker_sdk/sdk/api40/models.py, python/tests/rtl/test_serialize.py
Prior to this change python SDK would raise when the API returned an
invalid enum value. Given an enum type of `MyAPIEnum` and an invalid
value of `""` this error would be raised
`ValueError: '' is not a valid MyAPIEnum`
Now it will deserialize to `MyAPIEnum.invalid_api_enum_value`
Side note: I really wanted to but was unable to dynamically modify the
`MyAPIEnum.invalid_api_enum_value` enum member value to be the actual
invalid value returned by the API. So
`MyAPIEnum.invalid_api_enum_value.value` will always be
`"invalid_api_enum_value"`
=> Python SDK safe enum deserialization

packages/api-explorer/package.json, packages/api-explorer/src/components/DocCode/DocCode.tsx, packages/api-explorer/src/components/DocResponses/DocResponseTypes.tsx, packages/api-explorer/src/components/DocResponses/DocResponses.spec.tsx, packages/api-explorer/src/components/DocResponses/DocResponses.tsx, packages/api-explorer/src/components/DocResponses/index.ts, packages/api-explorer/src/components/DocResponses/utils.spec.ts, packages/api-explorer/src/components/DocResponses/utils.ts, packages/api-explorer/src/scenes/MethodScene/MethodScene.tsx, packages/api-explorer/src/scenes/MethodScene/components/DocResponse.tsx, packages/api-explorer/src/scenes/MethodScene/components/index.ts, packages/api-explorer/src/scenes/MethodScene/utils.spec.ts, packages/api-explorer/src/scenes/MethodScene/utils.ts, packages/run-it/package.json, yarn.lock
- Renamed `DocResponse` to `DocResponses` and moved it into global components folder
- Split `DocResponses` into `DocResponses` and `DocResponseTypes`
- Utility functions and tests for cleaning responses from unwanted metadata
- Made `json` the default language in `DocCode`, fixing a previous bug
PS: Updating @looker/components has broken the font
=> ApiExplorer: Refactored DocResponses according to design spec 

python/setup.py
looker_sdk [uses](https://github.com/looker-open-source/sdk-codegen/blob/a1c4acb61d727cc7a22368761b0bff2244747c61/python/looker_sdk/rtl/auth_session.py#L276) the `kw_only` feature of attrs, which was [introduced](https://www.attrs.org/en/stable/api.html#core) in 18.2.0.
I'm not _100% sure_ that this really is the minimum bound for `attrs` for looker_sdk (it could be higher), but the minimum bound is at least as low as this.
This became an issue for me while working with another library which specified `attrs==18.1.0`, causing runtime errors. If `looker_sdk` had included this pin, the pip install would have (correctly) failed. Of course, the other library shouldn't be pinning with `==` - I opened a PR there too.
=> Lower-bound python attrs requirement to 18.2.0

kotlin/build.gradle, kotlin/settings.gradle
This defines a project group and name which are necesssary so that the
kotlin sdk may be accessed as a project.  Until we have the project
published to a package distribution system, this allows us to use a
Gradle Source Dependency [1] to embed the project.
Also changes a few `compile` dependencies to their newer versions to
remove deprecation warnings from gradle.
[1] https://blog.gradle.org/introducing-source-dependencies
=> Fixes to support embedding in other projects

packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts, python/looker_sdk/rtl/model.py, python/looker_sdk/rtl/serialize.py, python/looker_sdk/sdk/api31/methods.py, python/looker_sdk/sdk/api40/methods.py, python/tests/integration/api31/test_methods.py, python/tests/integration/api40/test_methods.py, python/tests/rtl/test_serialize.py
The python SDK now accepts dictionaries as method bodies in addition to
the original model class instances. E.g. these are equivalent:
```
sdk.create_user({"first_name": "Jane", "last_name": "Smith"})
sdk.create_user(models.Writeuser(first_name="Jane", last_name="Smith"))
```
Note: static type checking fails on the first example but the assumption
is that users who opt for that form are not interested in type safety
Additionally, model class instances returned by the API act like
dictionaries. So you can do this:
```
me = sdk.me()
me["locale"] = "uk"
sdk.update_user(me["id"], me)
```
Note: the SDK will not do anything to prevent sending read-only
properties - the caller is responsible for the API's behavior in such
cases.
The dictionary-like behavior of model class instances is nearly …
=> Python SDK: enable models as dictionaries

.editorconfig, kotlin/README.md, kotlin/src/main/com/looker/rtl/ApiSettings.kt, kotlin/src/main/com/looker/rtl/AuthSession.kt, kotlin/src/main/com/looker/rtl/OAuthSession.kt, kotlin/src/test/TestApiSettings.kt, kotlin/src/test/Utils.kt
This should allow for simpler overriding of behavior, allowing clients
to provide a custom dict rather than requiring that they use the INI
format.
=> Change ApiSettings to accept a Map instead of Ini text

kotlin/src/main/com/looker/rtl/OAuthSession.kt, kotlin/src/test/TestAuthSession.kt, python/looker_sdk/rtl/auth_session.py, swift/looker/Tests/lookerTests/authSessionTests.swift, swift/looker/Tests/lookerTests/methodsTests.swift, swift/looker/rtl/apiConfig.swift, swift/looker/rtl/apiMethods.swift, swift/looker/rtl/apiSettings.swift, swift/looker/rtl/authSession.swift, swift/looker/rtl/authToken.swift, swift/looker/rtl/baseTransport.swift, swift/looker/rtl/oauthSession.swift, swift/looker/rtl/transport.swift
This also includes making the rest of the Swift SDK RTL open and/or public for access outside of the forthcoming package
=> Base64 OAuth for Kotlin and Swift SDKs

swift/looker/rtl/oauthSession.swift
My bootleg base64url encoding algorithm was slightly incorrect. Turns out the server throws fits without the `=` padding on the string.
=> Don't remove base64 padding going to base64url.

packages/run-it/src/components/RunItStyle/RunItStyle.tsx, packages/run-it/src/components/RunItStyle/index.ts
Just like in `ExplorerStyle.tsx`, `RunItStyle.tsx` should contain all `RunIt` styles (wrappers and any styling constants). This is not needed for cases where the styling requirements can be achieved using a simple prop to a Looker styled component without the need for a wrapper.
cc @miketorosian
=> RunIt: Add RunItStyle directory

packages/api-explorer/src/components/DocSDKs/DocSDKs.tsx, packages/api-explorer/src/components/DocSDKs/index.ts, packages/api-explorer/src/components/DocSdkUsage/DocExamples.tsx, packages/api-explorer/src/components/DocSdkUsage/DocSdkUsage.tsx, packages/api-explorer/src/components/DocSdkUsage/index.ts, packages/api-explorer/src/scenes/MethodScene/MethodScene.tsx
TODO:
- Replace hardcoded index with an asynchronous index fetch at first render
- In DocExamples, replace href links with full github links
- In DocExamples, replace link text to example summary
=> Api Explorer: Support example index searching and rendering

packages/api-explorer/src/components/DocMarkdown/utils.ts, packages/api-explorer/src/components/DocResponses/DocResponseTypes.tsx, packages/api-explorer/src/components/DocSDKs/DocSDKs.tsx, packages/api-explorer/src/scenes/MethodScene/MethodScene.tsx
**The problem**: The default selected media type in `DocResponseTypes` was previously being set once, as a default state value. On navigation to another method, the component received a `responses` object but the default `mediaType` state did not change. As a result, there were cases where the new `responses` object did not have a key matching the default media type previously set on first render causing the app to fail to render the whole scene.
A bug of this nature is also manifesting itself in other components, most notably in `DocSDKs` where the content rendered stays the same as one switches from one method (or type) to another.
**Solution**: In components where there's a link between props and state, there should be a `useEffect` which listens to props changes and updates state …
=> API Explorer: Fix stale state render bug

packages/sdk-rtl/src/oauthSession.spec.ts, packages/sdk-rtl/src/oauthSession.ts
For now it must not be 2^n so that Looker correctly treats it as base64 encoded
=> TS SDK oauth session code-verifier tweak

csharp/rtl/SdkUtils.cs, csharp/rtl/Transport.cs
Howdy!
Just wanted to contribute some fixes back after using the C# SDK for a project at work.
- https://github.com/looker-open-source/sdk-codegen/commit/02bc30021eebbb5b864b670595fd3f42f42cbbb7 ignores null values when serialising JSON requests because some APIs didn't play well with null values being included
- https://github.com/looker-open-source/sdk-codegen/commit/7f1166e1ef2d50678c3b39e8ae8f57a21b330f63 fix string interpolation  when calling `EncodeParam`
- https://github.com/looker-open-source/sdk-codegen/commit/43ab86aab0efc22f10bcb687adb4f6109b4a80cc call `AddQueryParams` when constructing a url
=> Various C# fixes

packages/sdk-codegen/src/typescript.gen.spec.ts, packages/sdk-codegen/src/typescript.gen.ts
make methodSignature and httpCall be flatter. This avoids some
extraneous trailing whitespace in tests. No change in generated code
because prettier runs and fixes it all anyway.
=> Typescript - reformat calls to be flatter

python/setup.py
Ran into a weird edge case today where import for `looker_sdk` failed because of a version issue with `attrs`, which was on `19.3.0` but `cattrs` required `attr>=20.1.0` ([this line](https://github.com/Tinche/cattrs/blob/1ab1cb27b0ee76d34ad8310d300329fba97a8f3a/src/cattr/converters.py#L16) requires [attrs > 20.1.0](https://www.attrs.org/en/stable/api.html#attr.resolve_types)). Tracelog below, but running a `pip install -U attrs` fixed the issue. Bumping it up in here, along with the version (feel free to update the version appropriately if that's an error on my end).
Tracelog:
```sh
...
/opt/conda/lib/python3.7/site-packages/looker_sdk/__init__.py in <module>
25 from looker_sdk.rtl import api_settings
26 from looker_sdk.rtl import requests_transport
---> 27 from looker_sdk.rtl import …
```
=> [Python] Bump attrs, caters versions for Python 3.7+

packages/api-explorer/scripts/appconfig.json
`devServer` is no longer running on `https` and `appconfig.json` needed to be updated.
=> ApiExplorer: Modify app config to reflect dev server config changes

examples/python/Pipfile, examples/python/content_validator_comparison.py, python/CHANGELOG.md, python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/setup.py, python/tests/rtl/test_auth_session.py
Moved headers down into the transport_options bag.
Called out the explicit "per-request" transport options shape.
Fixed example that broke a while ago :-()
closes #387
=> Python RTL transport interface headers cleanup

bin/smoke, bin/unit_test, python/tests/integration/.env, python/tests/rtl/.env, python/tox.ini
CI will actually call "tox -e unit" and "tox -e integration" per the
[github actions docs](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox)
using the python-versions matrix rather than relying on tox native
multi-python version testing. CI will set TOX_JUNIT_OUTPUT_DIR and
TOX_JUNIT_OUTPUT_NAME to approriate values for CI artifact uploading
Local tox usage will execute from from bin/smoke and bin/unit_test
which will rely on the generative envlist for a matrix of version/type
testing
=> Python separate bin/{smoke,unit}

packages/hackathon/README.md, packages/hackathon/src/data/sheets_client.ts, packages/hackathon/src/models/Hacker.ts
This fix falls back to using all roles for all users. If all roles fails, thats okay as the kind of user that does not have access to all roles will not care about the roles of other users.
=> Getting roles for each user was very slow

.github/scripts/wait_for_looker.py, .github/workflows/python-ci.yml, python/tox.ini
Run unit and integration tests using Github Actions.
Some notes for future consideration:
* It would be really nice if GA supported yaml anchors/aliases to DRY
out the configuration. An alternative could be to use [composite run
steps](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action)
but keeping it simple and slightly duplicated for now.
* See TODOs about integration tests on windows and macos
* I wanted to include a "LOOKER_LATEST" version variable so that the
windows and macos job config blocks could reference it and not have
to be changed each time a new looker version is added but currently
the "env" and "secrets" contexts aren't available and job level
configuration syntax
=> Python CI workflow

.github/workflows/python-ci.yml
* checkout/run code from PR (that's the default for pull_request but not
for pull_request_target)
* use auto-cancel action to cancel earlier unfinished jobs
* add "CI:TEST" label support
=> Misc python-ci workflow enhancements

.github/workflows/python-ci.yml
I misunderstood the security boundary for the pull_request_target event.
Apparently we should not be running code from forked PRs as it can gain
access to the github token which has access to our github secrets.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests
=> Do not auto run CI on forked PRs

.github/workflows/python-ci.yml, .github/workflows/python-release.yml, .github/workflows/release-please.yml
Python CI
* remove "if: false" for integration tests to re-enable
* only trigger on files under python/
* add "Twine upload check" as part of CI so we avoid that pitfal when
publishing
* More intelligent "Remove CI:TEST Label" conditional that will skip the
whole job rather than start the job and skip the single step
Python Release
* trigger on release/edited so that marking a release as non-draft will be
the condition for publishing to PyPI
Release Please
* stop using secrets.RELEASE_PLEASE_TOKEN - we no longer want to have
the release-please-action's side-effects trigger other workflows.
* We'll have a separate solution for running CI on a Release PR prior
to merging it
* we're no longer publishing on "release/published".
=> chore: python ci/release workflow tweaks

packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts
The makeTheCall work broke how a DelimSequence is referenced in methods.py
Fixed and added a test (we really need codecov)
fixed but not tested: if we ever reference an enum as a methods argument
it will also be namespaced appropriately with the models. package prefix
=> fix(codegen-python): fix DelimSequence references in methods

go/example/main.go, go/rtl/auth.go, go/rtl/auth_test.go
It turns out that the string was marshalled with quotes
for instance https://test.looker.com:443/api/4.0/users/search?email="foo@bar.com"
instead of https://test.looker.com:443/api/4.0/users/search?email=foo@bar.com
causing the server to ignore it.
=> Fixes an issue with Golang API requests containing strings

packages/api-explorer/package.json, packages/extension-api-explorer/package.json, packages/hackathon/package.json, packages/run-it/package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-utils/package.json, packages/sdk-codegen/package.json, packages/sdk-node/package.json, packages/sdk-rtl/package.json, packages/sdk/package.json, packages/wholly-sheet/package.json
Corrected babel's out dir when running in watch mode. Prior to this, webpack was not recompiling when for example APIX's dev server was running and a change was made in one of APIX's dependencies, such as RunIt.
=> Fixed dev environment

package.json, packages/extension-api-explorer/package.json, packages/hackathon/package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-utils/package.json, packages/sdk-codegen/package.json, packages/sdk-node/package.json, packages/sdk-rtl/package.json, packages/sdk/package.json, yarn.lock
There are now two watch commands
yarn watch - watches for changes and builds for browser based development
yarn watch:cjs - watches for changes and builds for node based development
In addition, updated extension-sdk-react package for extensions (fixes an issue with browser backward/forward buttons)
=> yarn watch changes

packages/sdk-codegen/src/codeGen.ts, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts
Currently the Python generator defines dictionaries using the `dict()` function, e.g. `dict(k1 = "v1", k2 = "v2")`. 
This generates incorrect syntax when the key contains periods or other special characters like hyphens, as it requires it to be quoted, e.g. `dict("foo.bar" = "v1")`. Additionally, passing keyword arguments into `dict()` is risky if the keys are not valid Python identifiers, e.g. `import`. 
Initialize dictionaries using curly braces as it works for all kinds of keys. 
- Added `hashKeyQuote` and `hashSetSep` attributes to `ICodeGen`
- Removed overriding `argSet` method in PythonGen
Note that currently we do not capture the key types and all keys are quoted. This is a bug that is unlikely to be experienced but might need fixing later on. See …
=> Fixed Python makeTheCall dictionary syntax

packages/sdk-codegen-scripts/src/legacy.ts, packages/sdk-codegen-scripts/src/legacyGenerator.ts, packages/sdk-codegen/src/codeGenerators.ts
```sh
yarn
yarn build
yarn legacy java
````
will generate a Java SDK to `/api/4.0/java` using the API 4.0 specification
The package name arguments may need additional tweaks. I didn't attempt to build the SDK, just invoke the OpenAPI generator for Java to emit it.
=> Added definition for a legacy Java SDK generator

package.json, packages/sdk-codegen-scripts/package.json, packages/sdk-codegen-scripts/src/fetchSpec.ts, yarn.lock
Deleted @spotlight/json and @spotlight/spectral packages, the latter of which was using an older version immer.
immer is no longer referenced
Deleted deleted code that referenced @spotlight/json package
=> Dependabot fix for immer

packages/sdk-codegen/package.json, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/specConverter.spec.ts, packages/sdk-codegen/src/typescript.gen.spec.ts
Trying to simplify the dependency graph just a tad. Currently sdk is not
needed by sdk-codegen but if we do need it in the future I'd suggest
we copy in by hand the required interfaces/values etc
=> refactor: remove sdk-codegen's dep on sdk

.github/semantic.yml
Since we always squash/merge, it is really the PR title we are about more
than individual commit titles. On that note, we should consider
only allowing squash/merge on sdk-codegen
=> chore: configure semantic PRs to only care about the PR title

packages/extension-sdk/package.json, packages/extension-sdk/src/connect/extension_host_api.spec.ts, packages/extension-sdk/src/connect/extension_host_api.ts, yarn.lock
Firefox does not allow Error objects to be serialized over chatty message channel. This fix upgrades chatty to pick up a fix whereby chatty serializes error messages. It also fixes extension sdk handling of uncaught errors to only send the error message rather than the error object.
=> fix: firefox chatty serialization error

python/README.rst
The paragraph looks a bit weird. Perhaps the "Setting environment variables" was meant to be linked?
=> docs: Linkify the link for setting environment variable in Readme

.github/workflows/python-publish.yml
was able to publish looker_sdk-v21.0.0 to pypi off a branch using the
workflow_dispatch. I assume the `release` event will still work but
we'll have to wait till a new release is created/published to find out.
=> chore: working version of python-release

packages/sdk-codegen-scripts/README.md, packages/sdk-codegen-utils/README.md, packages/sdk-codegen/README.md
changed "direct use" to "indirect use"
=> chore: Update deprecated sdk-codegen package text

.github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
by applying the CI:HOLD label you can avoid triggering
CI runs. This is mostly useful if you expect a lot of
thrashing on your PR before it is actually ready for tests
=> ci: support a CI:HOLD label

.release-please-manifest.json, packages/api-explorer/CHANGELOG.md, packages/api-explorer/package.json, packages/extension-api-explorer/package.json, packages/hackathon/package.json, packages/run-it/package.json, packages/wholly-sheet/package.json
@looker/api-explorer => 0.9.0
@looker/run-it => 0.9.0
@looker/wholly-sheet => 0.5.0
=> chore: reset versions on unpublished packages

packages/sdk-codegen-scripts/src/fetchSpec.ts, packages/sdk-codegen-scripts/src/legacyGenerator.ts, packages/sdk-codegen/src/codeGenerators.ts
- Fixed the issue with the legacy generator (it was missing an `await` after recent spec processing changes)
- Corrected the php legacy language declaration and left it active
- Corrected legacy language declarations that are still commented out
update and use the legacy generator with:
```sh
yarn && yarn build
yarn legacy php
```
Fixes #442 🦕
=> fix: legacy generator was broken

.github/workflows/python-ci.yml, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/python.gen.ts, python/looker_sdk/__init__.py, python/looker_sdk/rtl/api_methods.py, python/looker_sdk/rtl/serialize.py, python/looker_sdk/rtl/transport.py, python/looker_sdk/sdk/api31/methods.py, python/looker_sdk/sdk/api31/models.py, python/looker_sdk/sdk/api40/methods.py, python/looker_sdk/sdk/api40/models.py, python/tests/conftest.py, python/tests/integration/test_methods.py
Update the python SDK to expose these methods on the Looker API.
BREAKING CHANGE: sdk.login, sdk.logout, and sdk.login_user will now
behave exactly as the Looker API spec describes. The previous behavior
can still be accessed via sdk.auth.login, sdk.auth.logout, and
sdk.auth.login_user
=> fix!: python sdk login, login_user, logout methods

packages/sdk-codegen-scripts/README.md, packages/sdk-codegen-scripts/src/sdkGen.ts, packages/sdk-codegen-scripts/src/utils.ts
- for SDKs that support streaming, this skips generating the `streams` file. It does *not* remove any existing streams files, or change any other generated files
- expanded the `-h` display
- invalid gen options are rejected with an error
- recognize 'all' as a valid language switch but it can still be overridden if other language specifiers are used, so it's undocumented
=> feat: added -n | --nostreams to code generator options

release-please-config.json
The python SDK had a breaking change which caused these semver packages to
major bump - not what we want right now.
=> chore(release-please): fix release-as for sdk-codegen and sdk-codegen-all

python/looker_sdk/rtl/auth_session.py, python/looker_sdk/rtl/requests_transport.py, python/looker_sdk/rtl/transport.py, python/tests/rtl/test_auth_session.py
Now auth_session login/logout/login_user will pass along any original
transport_options from the sdk call.
Fixes #541 🦕
=> fix: auth_session uses transport_options

yarn.lock
I don't think this is required for release
=> chore: check in updated yarn.lock

.github/workflows/codegen-ci.yml, release-please-config.json
bump-patch-for-minor-pre-major setting preserves the standard
"only bump patch number for both features and fixes". This
augments the setting to "only bump the minor version for
breaking changes"
=> chore: codegen-ci fix and rp config tweak

packages/sdk-codegen/src/codeGen.ts
=> fix: add missing bumper method to ICodeGen

packages/api-explorer/src/components/SideNav/SideNav.spec.tsx, packages/api-explorer/src/components/SideNav/SideNav.tsx, packages/api-explorer/src/components/SideNav/SideNavMethods.tsx
=> fix: remove search criteria selector and auto expand results

packages/sdk-codegen/src/sdkModels.spec.ts, packages/sdk-codegen/src/sdkModels.ts, test/openApiRef.json
=> fix: recursive search of direct type references

release-please-config.json
based on conventional commits(e.g. the `feat: Typescript SDK tree-shaking support`)  + semver, this package would ordinarily bump to 21.6.0.
the remaining looker-versioned packages don't need an explicit release-as **this time** because they're only being patch bumped anyway by release-please/node-workspace (the lerna-based dependency version bumping)
=> chore: relase-please sdk release-as 21.4.1 for #580

kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/test/TestMethods.kt, packages/sdk-node/src/nodeTransport.ts, packages/sdk-node/test/methods.spec.ts
We have an outstanding feature request to improve analysis of Kotlin SDK errors, but this documents the encountered error in the Typescript SDK test, which has better error handling
API Explorer and the existing Looker API Docs UI can also be used to see what the actual 422 error is
Fixes #544 🦕
=> fix: error handling for TS SDK, GSon body serialization for Kotlin SDK

release-please-config.json
Part of our "non-Looker-release" release cycle needs to be resetting
"release-as" keys so we can see what release-please would propose
normally based purely on conventional commits and THEN we can
make the necessary "release-as" adjustments
=> chore: reset release-please release-as config

.github/workflows/lerna-publish.yml, .github/workflows/python-publish.yml, release-please-config.json
prior to this change the lerna publish workflow could only be triggered
by a manual run. Now it will go as soon as release-please creates the
release (which happens right after the Release PR is merged)
=> chore: publish workflows go automatically now

packages/api-explorer/src/components/DocSDKs/DocSDKs.spec.tsx, packages/run-it/src/components/DocSdkCalls/DocSdkCalls.spec.tsx
Usage of the deprecated `label` attribute in these tests were causing the latest Api Explorer build to fail
=> fix: removes deprecated object attribute reference

packages/sdk-codegen/src/codeGen.ts, packages/sdk-codegen/src/csharp.gen.spec.ts, packages/sdk-codegen/src/csharp.gen.ts, packages/sdk-codegen/src/go.gen.spec.ts, packages/sdk-codegen/src/go.gen.ts, packages/sdk-codegen/src/kotlin.gen.ts, packages/sdk-codegen/src/pseudo.gen.spec.ts, packages/sdk-codegen/src/pseudo.gen.ts, packages/sdk-codegen/src/python.gen.spec.ts, packages/sdk-codegen/src/swift.gen.spec.ts, packages/sdk-codegen/src/swift.gen.ts, packages/sdk-codegen/src/typescript.gen.spec.ts, packages/sdk-codegen/src/typescript.gen.ts
`noComment` defaults to `false`, retaining current generator behavior
`noComment = true` omits comments from code generation.
This option was primarily added for usage with API Explorer
Fixes #626 🦕
=> feat: add noComment toggle to code generators

packages/extension-sdk/README.md, packages/extension-sdk/src/connect/connect_extension_host.spec.ts, packages/extension-sdk/src/connect/types.ts, packages/run-it/src/components/ShowResponse/ShowResponse.spec.tsx
The Looker host type is sent in the lookerHostData parameter of the initialization message.
Looker host type can be
1. standard - standard chromed Looker UI.
2. embed - embedded extension.
3. spartan - spartan extension.
Requires Looker 21.8.
In addition the
1. hostUrl has been deprecated in favor of hostOrigin (hostOrigin reflects more accurately what the contents of the parameter contains)
2. mountType - extension mount type. Currently fullscreen. In preparation for alternative mount points in the future.
=> feat: extension framework identifies looker host type

package.json, packages/api-explorer/package.json, packages/api-explorer/src/ApiExplorer.tsx, packages/api-explorer/src/utils/envAdaptor.spec.ts, packages/api-explorer/src/utils/envAdaptor.ts, packages/api-explorer/src/utils/index.ts, packages/code-editor/package.json, packages/extension-api-explorer/src/ExtensionApiExplorer.tsx, packages/extension-api-explorer/src/utils.spec.ts, packages/extension-api-explorer/src/utils.ts, packages/run-it/package.json, yarn.lock
APIX will use google fonts when running as a non embedded extension OR, in stand alone mode, when running from a looker.com or google.com domain.
Also
1. adds extension-api-explorer package to apix tests script.
2. fixes looker design token dependencies. missing or wrong version from some packages. specifies an explicit version as an alpha version is the current version in npm.
=> feat: APIX now uses google font appropriately

packages/extension-api-explorer/README.md
local_storage is required for the APIX extension
=> docs: correcting manifest for extension APIX

.github/release-please.yml
this bot is google-cla approved AND should cause CI to run automatically
as well as publishing-after-release-creation to happen automatically
the action cannot perform either because it is an imposed limitation
in GitHub actions that a side effect of one action cannot trigger another action
=> chore: try release-please bot as action replacement

packages/api-explorer/src/reducers/index.ts, packages/api-explorer/src/reducers/search/index.ts, packages/api-explorer/src/reducers/spec/index.ts, packages/api-explorer/src/utils/index.ts, packages/run-it/src/components/ConfigForm/configUtils.ts, packages/run-it/src/components/ConfigForm/index.ts, packages/run-it/src/components/index.ts, packages/run-it/src/index.ts
Standalone and extension APIX developer and bundle builds were displaying import/export warning messages. This change fixes those warning messages.
The downside to this change is that we may be exporting functions and types that may not need to be exported. There should be another exercise to go through and clean up index files for lower level components such that only types and components that actually need to be exported are exported.
=> chore: fix annoying warnings from APIX builds

.github/release-please.yml, .github/workflows/release-please.yml
better to stick with an action than switch to the app:
1. app we cannot see logs nor execution success/failure
2. configuration is more transparent through action than app
=> chore: use looker-open-source-automation-bot token for release-please

.github/workflows/codegen-ci.yml, .github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
- get rid of CI:TEST/HOLD label logic
-- this was causing problems: when other labels were applied
(e.g. "cla: yes") then the workflow would report as skipped
and it appeared that all checks passed.
-- replacement: go to the actions UI, and for each CI workflow trigger
it on your branch
- add "noop" duplicate/dummy jobs to support enabling "required checks"
on PRs so that we no longer accidentally merge broken changes.
See code comments and
https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586/7?u=joeldodge79
This will allow us to enable the following required checks on PRs
* Python Test Results
* Typescript Test Results
* Codegen Test Results
* cla/google
* Semantic Pull Request
=> chore: CI overhaul

release-please-config.json
the `minor-pre-major` flags should be top level defaults
code-editor was missing them causing incorrect version
bumping for that package
=> chore: release-please config fix

.github/workflows/codegen-ci.yml, .github/workflows/noop-ci.yml, .github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
The benefit of having them duplicated in each workflow
file was the ability to delay their execution with the
`needs: [publish-test-results]` syntax. However, there
was buggy behavior where the python-ci workflow would
get attributed the actual jobs from the tssdk-ci workflow
and its own noop jobs would somehow fail with the
opaque `No such file or directory` error
The downside of centralizing them is losing the ability to
specify that `needs` syntax. I believe that means they
will "pass" immediately and there will be a window of
several minutes until the "real" jobs report where the PR
will satisfy all the required checks and could be
mergeable. If that is the case, I may consider hacking it
to do `sleep 300 && exit 0` which would introduce an
artifical delay that may or may not help …
=> ci: centralize noop checks

packages/api-explorer/src/components/ExploreType/ExploreProperty.tsx, packages/api-explorer/src/components/ExploreType/ExploreType.tsx, packages/api-explorer/src/components/ExploreType/index.ts, packages/api-explorer/src/components/Header/Header.tsx, packages/api-explorer/src/components/Link/Link.tsx, packages/api-explorer/src/components/Link/index.ts, packages/api-explorer/src/components/SideNav/SideNavMethods.tsx, packages/api-explorer/src/components/SideNav/SideNavTypes.tsx, packages/api-explorer/src/index.tsx, packages/api-explorer/src/scenes/TagScene/TagScene.tsx, packages/code-editor/src/Markdown/Markdown.tsx, packages/hackathon/src/components/SideNav/SideNav.tsx
Improvements to the Looker Tree and NavLink components can be used to clean up the Type Explorer
Changes may include but may exceed:
- left nav
- `ExploreType`
- `ExploreTypeLink`
- `ExploreProperty`
- other `ExplorerProperty*` components
=> refactor: improve ExploreType.tsx UI/UX

packages/extension-api-explorer/src/Loader.tsx, packages/hackathon/src/components/Loading/Loading.tsx, packages/run-it/src/components/Loading/Loading.tsx, packages/run-it/src/components/ShowResponse/responseUtils.spec.tsx, packages/run-it/src/components/ShowResponse/responseUtils.tsx, packages/run-it/src/test-data/index.ts, packages/run-it/src/test-data/responses.ts
- also changed to `ProgressCircular` "processing" component
- fixed text color on RunIt response progress indicator
=> feat: syntax highlight application/sql responses

packages/sdk-codegen-scripts/src/sdkGen.ts, packages/sdk-codegen-scripts/src/sdkGenerator.ts
When the `-n` option is used for the code generator, the tally comments at the top of each generated source file are also removed.
Consider it "no comment" as well as "no streams"
=> chore: noStreams skips tally headers in generated source

python/looker_sdk/rtl/serialize.py, python/tests/rtl/test_serialize.py
we'd forgotten to register a `cattr.register_unstructure_hook` for `datetime.datetime` objects.
Clearly no one had been trying to send in any data that included a datetime.datetime till now
closes #720
=> fix: python datetime [de]serialization bug

packages/sdk-node/src/nodeTransport.spec.ts, packages/sdk-node/src/nodeTransport.ts, packages/sdk-rtl/src/baseTransport.ts, packages/sdk-rtl/src/browserTransport.ts
`422` and other "not ok" statuses were being left as `ok: true` with the recent raw request observer implementation. This fixes the bug.
=> fix: check HTTP status code for TS SDK "ok" toggle

packages/api-explorer/src/ApiExplorer.tsx
While walking the dog I realized that it was not necessary to use useRef to hold the current value of the toggle. The alternative is to pass a function to setState that accepts the current value. This change does that.
=> feat: simplify apix dev portal navigation toggle

packages/run-it/src/RunIt.tsx, packages/run-it/src/components/DataGrid/gridUtils.spec.tsx, packages/run-it/src/components/DataGrid/gridUtils.tsx, packages/run-it/src/components/DataGrid/index.ts, packages/run-it/src/components/ShowResponse/ShowResponse.spec.tsx, packages/run-it/src/components/ShowResponse/ShowResponse.tsx, packages/run-it/src/components/ShowResponse/responseUtils.tsx, packages/run-it/src/test-data/index.ts, packages/run-it/src/test-data/responses.ts
APIX now renders raw data if it cannot parse the response returned as expected.
1. Added try/catches in appropriate places. Note that the try/catch in RunIt is probably NOT necessary but the code being wrapped indicates that an error could be thrown (logically it should never happen as the user should always be authenticated).
2. Renamed `parseJson` method to `json2Csv` to better reflect what it does (I was initially confused by the original method name).
3. Created a ShowRaw response handler.
4. Created a fallbackResponseHandler to use ShowRaw.
=> fix: bullet proof APIX response handling

examples/python/README.md, examples/python/folder_permission_access.py
Example python SDK script to construct and output an object detailing content access metadata for each folder, showing how to recursively traverse the folder tree. For each folder, the object will contain a list of Groups and Users who have either been explicitly been granted view/edit access to the folder, or implicitly given via inheritance from a parent folder.
=> feat: adding python example for folder permission access

.envrc
I was making a similar change in the `embed-sdk` repo. It was suggested I test for nix before using nix to be nice to non nix users. Propagating that fix here.
Note, you will need to run `direnv allow` again.
=> chore: Add nix present check to .envrc

packages/extension-api-explorer/src/ExtensionApiExplorer.tsx
APIX Extension was failing in latest master with invalid json. This was with the published extension AND the development version. Not sure why it suddenly started failing.
=> fix: apix fix

.github/workflows/python-ci.yml, python/setup.py
we no longer have support@looker.com and this field only accepts
a valid email address. sadly twine check does not catch this error
yet, hopefully it will some day.
Factored the twine check out of the unit matrix: it only needs to run once
=> fix: remove python setup.py author_email

packages/sdk-codegen-scripts/scripts/refresh_specs.ts, packages/sdk-codegen-scripts/scripts/utils.ts, packages/sdk-codegen-scripts/src/convert.spec.ts, packages/sdk-codegen/src/specConverter.ts
We changes spec fetching to async which made `yarn refresh` fail
=> fix: spec refresh

packages/sdk-rtl/package.json, packages/sdk-rtl/src/browserTransport.ts, packages/sdk-rtl/src/transport.ts
TypeScript 4.4 assigns errors the type `unknown` by default in catch clauses. This PR supplies the necessary assertions to safely extract the `message` field in `browserTransport.ts`, and rethrows the error if it fails to meet these expectations.
=> fix: placate TypeScript 4.4

packages/api-explorer/src/scenes/MethodScene/utils.spec.ts, packages/api-explorer/src/scenes/MethodScene/utils.ts, packages/code-editor/src/CodeDisplay/CodeDisplay.tsx, packages/run-it/src/components/LoginForm/LoginForm.tsx, packages/run-it/src/components/RequestForm/FormItem.tsx, packages/run-it/src/components/RequestForm/RequestForm.spec.tsx, packages/run-it/src/components/RequestForm/RequestForm.tsx, packages/run-it/src/components/RequestForm/formUtils.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx, packages/run-it/src/components/ShowResponse/responseUtils.tsx
Made some changes to the **RunIt** form, both for layout and editing various values
- enum values are now a string input instead of `{}`. There is an outstanding task to support a dropdown picker for enums that will come with the next significant change for the form editor
- DelimArray values are now a string input instead of `{}`
- all inputs are on a single line now, saving form space. This is particularly useful for endpoints with many input values
- date time picker is now a pop over with a button to choose the date (but still doesn't have time picking)
- the default action for the form is now the first button, making it more convenient for tabbing through
=> feat: lots of RunIt form cleanup

packages/run-it/README.md
The package was missing a readme.
=> docs: added RunIt README.md

packages/code-editor/src/CodeDisplay/CodeWrapper.tsx, packages/code-editor/src/Markdown/Markdown.tsx
No longer using the default yellow highlighting for search result matches in markdown text and code results
=> chore: update search highlighting style

packages/api-explorer/src/components/DocMarkdown/DocMarkdown.tsx, packages/code-editor/src/Markdown/Markdown.tsx
Clicking a link in markdown now works for extensions.
Fix is to rely on getAttribute method to get pathname and href values rather
than get pathname and href directly. Also, now tests if url begins with
the spec key as well as the pathname.
Possibly broken by markdown upgrade although why standalone was not
broken is puzzling
=> fix: Extension Api Explorer markdown link clicks

packages/api-explorer/src/components/SideNav/SideNav.spec.tsx, packages/api-explorer/src/components/SideNav/SideNav.tsx, packages/api-explorer/src/reducers/spec/utils.ts, packages/api-explorer/src/scenes/DiffScene/DiffScene.tsx, packages/api-explorer/src/scenes/TagScene/TagScene.tsx
Tabs in sidenav were not being synced with history. Now if tab selected,
history is updated. If page is reloaded, tabs are synced to current
history. If link is clicked that updates sidenav panel, panel is updated
accordingly.
=> fix: Sidenav selection

packages/sdk-codegen/src/kotlin.gen.spec.ts, packages/sdk-codegen/src/kotlin.gen.ts
This PR fixes generation of kotlin classes which handle properties having special characters.
Fixes #837 🦕
=> fix: Property names with special characters in Kotlin SDK

packages/run-it/src/utils/RunItSDK.ts, packages/run-it/src/utils/requestUtils.spec.ts, packages/run-it/src/utils/requestUtils.ts
Fixes the sporadic scenario where a `body` value of `{}` is sent to an endpoint. This update removes any "empty" body from the RunIt request submission
=> fix: remove body from REST call if no body elements are defined

packages/run-it/src/components/ShowResponse/ShowResponse.spec.tsx, packages/run-it/src/components/ShowResponse/responseUtils.spec.tsx, packages/run-it/src/components/ShowResponse/responseUtils.tsx, packages/run-it/src/test-data/index.ts, packages/run-it/src/test-data/responses.ts
Only truly 2D JSON data should have a grid. This fixes erroneous DataGrid rendering
=> fix: logic for 2D JSON data detection

packages/sdk-codegen/src/sdkModels.spec.ts, packages/sdk-codegen/src/sdkModels.ts, packages/sdk-codegen/src/typescript.gen.spec.ts
Change was made for APIX type tagging, and a scenario was missed that caused infinite recursion
=> fix: stack overflow for type tagging during codegen

packages/run-it/src/components/RequestForm/formUtils.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx, packages/sdk-node/test/methods.spec.ts
Body values that were already parsed were failing to parse (obviously) so the validation was failing.
I completely missed that scenario
This needs to be merged before  API Explorer is deployed because RunIt will not work for any endpoint with a body
Definitely need to add e2e tests for RunIt!
=> fix: validateBody for API Explorer

packages/run-it/src/RunIt.spec.tsx, packages/run-it/src/RunIt.tsx, packages/run-it/src/components/RequestForm/formUtils.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx
Body parameters that are required must be provided before RunIt will Run
=> feat: enforce required body parameters for RunIt

packages/api-explorer/src/state/settings/sagas.ts
The call of a saga from within another saga was resulting in issues for the extension version. This PR changes the way envAdapter methods are called from within sagas.
=> fix: api explorer initialization 

packages/hackathon/src/Hackathon.tsx, packages/hackathon/src/components/Loading/Loading.tsx, packages/hackathon/src/scenes/AdminScene/AdminScene.tsx, packages/hackathon/src/scenes/HomeScene/HomeScene.tsx, packages/hackathon/src/scenes/JudgingScene/JudgingScene.tsx, packages/hackathon/src/scenes/ProjectsScene/ProjectsScene.tsx, packages/hackathon/src/scenes/ResourceScene/ResourceScene.tsx, packages/hackathon/src/scenes/ResourceScene/resource_data.ts, packages/hackathon/src/scenes/UsersScene/UsersScene.tsx
- Updated Loading component to default to always display if not
passed in loading prop. Making it as dumb as possible
- Updated Loading rendering logic and styling in scene components
so layouts does not shift/change after loading is finished.
- Updated side nav to be thinner to accomodate smaller viewports
- Updated resources with new component and dataset tag
- Added header to each page for easier navigability
- Added hacker faq link to home/agenda page
- Added additional text and field styling to resource page for
better UX
=> fix: Hackathon styling and resource update

packages/hackathon/src/scenes/ResourceScene/ResourceScene.tsx, packages/hackathon/src/scenes/ResourceScene/resource_data.ts
- Add JOIN Yt videos to hackathon resources
- Updated resource tags and type to use enums for better maintenance
- Updated resource buttonitem rendering to be based off tags enum
=> fix: Add hackathon resources and refactor to use enums

packages/hackathon/src/scenes/HomeScene/HomeScene.tsx, packages/hackathon/src/scenes/HomeScene/agenda.ts, packages/hackathon/src/scenes/ProjectEditorScene/components/ProjectForm.tsx, packages/hackathon/src/scenes/ResourceScene/resource_data.ts
- Added video link and updated video link
- Updated agenda times and texts
- Also changed wording of judging consent toggle
=> fix: Updated and corrected agenda and resources page

packages/hackathon/README.md, packages/hackathon/src/data/add_user/sagas.ts, packages/hackathon/src/scenes/ResourceScene/resource_data.ts
Updated to match what is running in production
=> fix: Updated hackathon readme landing page path

.github/workflows/codegen-ci.yml, .github/workflows/lerna-publish.yml, .github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
Looker 21.20 support for CI.
The passwords are the same as for 20.18.
=> fix: Update CI to include Looker 21.20

packages/hackathon/src/scenes/HomeScene/HomeScene.tsx, packages/hackathon/src/scenes/HomeScene/components/agendaUtils.ts, packages/hackathon/src/scenes/ProjectsScene/ProjectsScene.tsx
- Judging time for the hackathon is always shown at the bottom of the project list now
- If judging has started:
- the judging start time is displayed to the left of the `Add Project` button
- if the user has the ability to lock projects, `Add Project` remains enabled
- if the user is a regular hackathon attendee, `Add Project` is disabled
- Made intro agenda on the home page display English or Japanese depending on the user's locale
=> feat: disable "Add Project" when judging starts

packages/hackathon/src/scenes/ProjectEditorScene/components/ProjectForm.tsx
Turns out invite only has not been implemented yet.
Removing UI option till it is implemented.
TODO work tracked in ticket.
=> fix: Remove hackathon invite only option

packages/hackathon/README.md, packages/hackathon/src/models/sheetUtils.tsx
`<Tooltip />` now requires an element
=> fix: make sheetCell always return a Span

swift/looker/rtl/transport.swift
The mobile team wants to modify the agent tag for the Swift SDK
=> chore: make Swift SDK agentTag customizable

.github/workflows/apix-ci.yml
Replaced apix ci call to `yarn build-extensions` with call to
`yarn lint:ts` to trigger TSC to catch typescript compilation errors.
Previously we called to `yarn build-extensions` to trigger tsc.
=> chore: Explicitly call tsc with yarn lint:ts in apix CI

release-please-config.json
`@looker/extension-utils` should be semver for now
=> chore: leave extension-utils as semver

packages/sdk-rtl/src/browserTransport.spec.ts
Verifies that whatever your JSON payload says, that's what you get in the TypeScript SDK (as expected)
=> chore: test JSON deserialization behavior for TS

csharp/csharp.csproj, csharp/rtl.Tests/TestUtils.cs, csharp/rtl.Tests/TransportTests.cs, csharp/rtl/Transport.cs
Look# SDK is forward and backward compatible for numeric/string id payloads
=> chore: test JSON deserialization for Look#

kotlin/src/test/TestTransport.kt
Verifying that JSON string or numeric representations "just work" for receiving DataClass type property conversion
=> chore: test JSON deserialization for Kotlin

go/go.mod, go/go.sum, go/rtl/auth.go, go/rtl/auth_test.go, go/rtl/types.go
Go SDK now supports unmarshaling string type -> num type and num type -> string type.
- Replaced std json with json-iterator to make use of its decoding extensibility
- Added unit test around fuzzy unmarshaling
- Updated unit tests to not depend on looker instance or looker.ini to facilitate CI builds.
- Replaced login() private method tests with Authenticate() public method tests and made them more comprehensive.
Will follow up with styling updates and CI workflow after this PR is merged.
=> fix: Made Go SDK json decoding fuzzy

packages/extension-api-explorer/src/ExtensionApiExplorer.tsx
- preferred UI for embedded API Explorer
- resolves partially obscured request form buttons at the bottom of long request forms
=> fix: use headless navigation mode for API Explorer as an extension

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/hackathon-ci.yml, .github/workflows/python-ci.yml, .github/workflows/required-checks-hack-ci.yml, .github/workflows/resources-ci.yml, .github/workflows/tssdk-ci.yml, docs/ci-testing.md
The basic problem we have is that we want to make certain checks required, but the tests for them don't run on all requests. For example this test only runs if the indicated paths are changed.
```
name: TypeScript SDK CI
on:
pull_request:
paths:
- packages/sdk/**
- packages/sdk-rtl/**
- packages/sdk-node/**
- packages/extension-sdk/**
- packages/extension-sdk-react/**
- packages/extension-utils/**
```
A special `required_checks_hack_ci` workflow would run. It would just sleep then mark the required checks as succeeded if they hadn't failed by 480 seconds. Every PR had to wait 480 seconds regardless.
My first version of this was to remove the path filters on pull requests and pushes, then use the a "check-files" reusable workflow that would set a bunch of flags based on what files changed. …
=> chore: new method to skip required checks

packages/api-explorer/e2e/e2e.spec.ts, packages/api-explorer/src/components/DocSDKs/DocSDKs.tsx, packages/api-explorer/src/utils/path.ts, yarn.lock
```ts
item instanceof Method
```
checks started failing for some obscure reason, so a new `isMethod()` check is now used
```sh
yarn test:apix && yarn test:apix-e2e
```
passes again. End-to-end tests needed to be updated for the `(Beta)` string also
=> fix: runtime error for API Explorer

go/rtl/constants.go, go/rtl/settings.go, go/rtl/settings_test.go
Also added unit tests for it that will leave existing environment variables undisturbed. (Will store env vars before test and restore env vars after test)
=> feat: Implemented Go SDK env var handling

go/rtl/auth.go
The original implementation was incorrect. Also added comment/doc to help avoid confusion if someone sets custom transport setting outside of the lookersdk verify ssl setting.
=> fix: Fixed incorrect VerifySSL setting implementation

.github/workflows/hackathon-ci.yml
- Added `yarn bundle` step to make sure hackathon can always be bundled
- Renamed and split up steps to be more descriptive
=> chore: Added bundle step and cleaned up hackathon CI

.github/workflows/go-ci.yml, .github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml
The looker versions for CI are all in one place now.
=> ci: change workflows to use reusable action for looker versions

packages/sdk-codegen-scripts/src/exampleMiner.spec.ts, packages/sdk-node/test/methods.spec.ts
Unit test tweak to support Looker 22.4 API type changes
=> chore: update unit test for string ID types

examplesIndex.json, packages/sdk-codegen-scripts/src/exampleMiner.ts, packages/sdk-node/test/methods.spec.ts
Turns out bazel build files have weird `stat`s that break node fs interrogation and hence break declaration miner.
This ignores errors reported on directory checking for those offending paths so indexing completes successfully
Hope to find a cleaner solution in the future but because this is an internal tool rarely used I don't want to spend more time on it right now
=> fix: declaration miner (internal utility)

go/integration/integration_test.go, go/rtl/auth.go, go/rtl/auth_test.go
Changes: 
- Go SDK Parse response based of type defined in go sdk models, the result type. This fixes methods returning string type. This handles all method result types, `string`, `struct`, `interface{}`.
- Added additional integration tests around queries, looks, and
dashboards. This fills out the basic integration test requirements.
- Added unit tests
- Return error body in addition to error status code for more descriptive response errors.
Ideally we want the content type header to be the source of truth when parsing the response. However, currently, go sdk model generation doesn't support union type for results, so we cannot parse according to Content Type Header. For now, parse based off result type.
Take for example [RunQuery](https://developers.looker.com/api/explorer/4.0/methods/Q …
=> fix: Make Go SDK parse response by result type

packages/sdk-rtl/src/transport.spec.ts, packages/sdk-rtl/src/transport.ts
`@looker/sdk-rtl` was encoding object values like
```ts
{ created_date: 'this year to second' }
```
as 
```ts
[object Object]
```
and now the value is JSON stringified instead
=> fix: encodeParam returned [object Object] for object types

packages/sdk-rtl/src/transport.ts
Release-please versioning was incorrect so the most critical package to get published didn't get published.
Updating the source comment header which should meet the criteria for republishing
=> fix: encodeParam doc tweak to republish

package.json, packages/api-explorer/src/ApiExplorer.tsx, packages/run-it/src/components/ConfigForm/ConfigForm.tsx, packages/run-it/src/components/RequestForm/RequestForm.tsx, packages/run-it/src/components/ResponseExplorer/ResponseExplorer.tsx, packages/run-it/src/utils/requestUtils.ts, packages/sdk-codegen/src/csharp.gen.ts, packages/sdk-codegen/src/kotlin.gen.ts, packages/sdk-codegen/src/swift.gen.ts, packages/sdk-codegen/src/typescript.gen.ts, yarn.lock
1. pinned to version 1.7.14 as 1.7.15 requires unsupported package.
2. overrode header rule to use a pattern for date.
3. fixed one lodash issue that arose.
4. ignored nested ternary issues. should be fixed but outside the
scope of what I want to do with this change.
The next published version of @looker/eslint-config-oss will include
the overridden header rule so the overridden header rule can be
removed then. Will investigate the unsupported package then.
=> chore: upgrade @looker/eslint-config-oss

packages/api-explorer/webpack.prod.config.js
Running `yarn run build` previously resulted in an empty (0b) output bundle.js
I believe this discrepancy was initially introduced inadvertently in https://github.com/looker-open-source/sdk-codegen/commit/fb8634fded843e3d9cbfeee2065fd70a8248b89e
=> fix: Update prod entrypoint to match dev entrypoint (App.tsx)

examplesIndex.json, packages/sdk-codegen-scripts/src/exampleMiner.spec.ts, packages/sdk-codegen-scripts/src/exampleMiner.ts
Browser permalinks should not end with `.git` in the repository name.
This PR updates the link root and the sdk example index
=> fix: example miner github permalinks do not use `.git` in the repository name

packages/sdk-codegen/src/testUtils/testUtils.ts
This is to clarify the values that are used for tests without having to look at the testUtils file to see what the values mean
Tagging this a chore because it's internal and shouldn't cause a version bump
=> chore: document testUtils.ts properties for sdk testing

examples/python/download_look.py
Looks like there was some cleanup to remove SDK-specific exception (0126ad978cd0b7df3daab3932d93bae307260bf4). This is cleanup of the final SDK exception reference in the `download_look.py` file.
I didn't open another bug as this addresses #756 but let me know if we want another bug ticket.
Fixes #756 🦕
=> fix: replacing unimported exception

packages/extension-sdk-react/src/components/ExtensionConnector/ExtensionConnector.spec.tsx, packages/extension-sdk-react/src/components/ExtensionConnector/ExtensionConnector.tsx, packages/extension-sdk-react/src/components/ExtensionConnector/types.ts, packages/extension-sdk-react/src/components/ExtensionProvider/ExtensionProvider.tsx, packages/extension-sdk-react/src/components/ExtensionProvider2/ExtensionProvider2.tsx, packages/extension-sdk-react/src/components/ExtensionProvider40/ExtensionProvider40.tsx, packages/extension-sdk-react/src/components/ExtensionProviderBase/ExtensionProviderBase.tsx, packages/extension-sdk/src/connect/extension_host_api.spec.ts, packages/extension-sdk/src/connect/tile/tile_sdk.spec.ts, packages/extension-sdk/src/connect/tile/tile_sdk.ts, packages/extension-sdk/src/connect/tile/types.ts, packages/extension-tile-playground/src/components/Inspector/components/EventTester/EventTester.tsx, packages/extension-tile-playground/src/components/Inspector/components/TileHostData/TileHostData.tsx
The major change here is that it became apparent that the ExtensionConnector
did not have an up to date copy of the provider data. This was okay because all of
the provider components merged the data received from the ExtensionConnector
with the existing data. As the ExtensionConnector was only passing partial
data this was okay. For extensions as tile however, the ExtensionConnector
needed to update other provider and was failing because it did not have the
latest data. This was due to the callbacks being called from the chatty api
and being unaware changes made to properties in the react render cycle. To
solve this provider data is now stored in a reference so the latest data
is always available. In addition, provider data updates are now explicitly
called out as partial updates.
The …
=> feat: implement receive tile host message

examplesIndex.json, packages/api-explorer/src/components/DocSource/DocSource.spec.tsx, packages/api-explorer/src/components/DocSource/DocSource.tsx, packages/sdk-codegen-scripts/scripts/mineDeclarations.ts, packages/sdk-codegen-scripts/src/declarationMiner.spec.ts, packages/sdk-codegen-scripts/src/declarationMiner.ts, packages/sdk-codegen-scripts/src/exampleMiner.ts, packages/sdk-codegen/src/declarationInfo.ts, packages/sdk-codegen/src/exampleInfo.ts
Added more `build` folders to ignore for the code miners. API Explorer was showing links to files that were build artifacts and don't get checked in to the repository, so they were dead links on the developer portal.
=> fix: remove generated files from examples index

packages/extension-sdk/src/connect/tile/types.ts, packages/extension-tile-playground/src/components/DashboardTile/DashboardTile.tsx, packages/extension-tile-playground/src/components/Inspector/components/TileHostData/TileHostData.tsx
Dashboard run start/end times now provided along with success information.
Allows extension to determin if the dashboard run button was pressed (or
auto run).
Example of usage provided.
=> feat: additional tile host data

packages/extension-sdk/src/connect/tile/tile_sdk.spec.ts, packages/extension-sdk/src/connect/tile/types.ts, packages/extension-tile-playground/src/components/Inspector/components/TileHostData/TileHostData.tsx
Provides additional information about the dashboard tile.
1. element id.
2. lastRunSourceElementId - populated when dashboard run is
initiated by an extension tile.
Also, minor fix to documentation.
Also, minor adjustment to tests.
=> feat: extension tile information

packages/api-explorer/src/scenes/DiffScene/DocDiff/DocDiff.spec.tsx, packages/api-explorer/src/scenes/DiffScene/DocDiff/DocDiff.tsx
also fixes a bug where we weren't rendering the first delta
Before:
After
=> fix: description sync issues in diff scene

docs/cors.md, examplesIndex.json, packages/extension-utils/README.md
Updated OAuth documentation to use `@looker/extension-utils` source references
=> docs: update OAuth and CORS docs

packages/api-explorer/jest-puppeteer.config.js, packages/api-explorer/jest.config.js, packages/api-explorer/package.json
prior to this change, debugging a unit test from inside the IDE was not possible.
To verify the fix:
1) run `yarn test:apix` from the root of the monorepo
2) run `yarn test:apix-e2e` from the root of the monorepo
3) try debugging a test
=> chore: separate unit and integration test configs

packages/api-explorer/src/components/SideNav/SideNavMethods.spec.tsx, packages/api-explorer/src/components/SideNav/SideNavMethods.tsx, packages/api-explorer/src/components/SideNav/SideNavTypes.spec.tsx, packages/api-explorer/src/components/SideNav/SideNavTypes.tsx
Enables side navigation methods panels to open and close properly. Previously, users were unable to close the expanded panel once opened.
=> fix: Sidenav Methods Panel Open & Closing

examples/ruby/README.md
Updated the Ruby SDK examples readme to point to the new location of the Ruby SDK
=> docs: correct Ruby SDK link in examples

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/hackathon-ci.yml, .github/workflows/lerna-publish.yml, .github/workflows/resources-ci.yml, .github/workflows/tssdk-ci.yml
API Explorer workflows are now failing when they should have in PR #1117 
This PR is to fix it
=> chore: update workflows for node 16

.github/workflows/tssdk-ci.yml
There are some dependencies that don't support node 18.
=> chore: drop node 18 from TS SDK CI

release-please-config.json
release config is back to the default config after 22.10.1
=> chore: reset release config

packages/sdk-rtl/src/apiMethods.spec.ts, packages/sdk-rtl/src/browserTransport.ts, packages/sdk-rtl/src/errorDoc.spec.ts, packages/sdk-rtl/src/errorDoc.ts
Retrieves the best match error code document for the provided error url from an API error payload
See `errorDoc.spec.ts` for an implementation example
=> feat: error code document retrieval

kotlin/README.md, kotlin/src/main/com/looker/rtl/AuthToken.kt, kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/test/TestMethods.kt, kotlin/src/test/TestTransport.kt
Added `parseSDKError()` to extract Looker API error payloads from error responses
=> feat: capture error details for the Kotlin SDK

packages/sdk-rtl/src/lookerSDKError.ts
fields should not be null if we have `errors` info in the response
=> fix: IErrorDetail fields should not be null

packages/api-explorer/src/scenes/DiffScene/DocDiff/DocDiff.spec.tsx, packages/api-explorer/src/scenes/DiffScene/DocDiff/DocDiff.tsx, yarn.lock
When comparing two specs in APIExplorer's Diff Scene, the scene will display the correct number of diff entries according to the page size, which is 15 by default.
=> fix: DiffScene Page Displays Accurate Number of Diff Entries

examples/python/content_validator_comparison.py, examples/python/create_db_connections.py, examples/python/disable_users_by_email.py, examples/python/download_tile.py, examples/python/logout_all_users.py, examplesIndex.json
**examples/python/content_validator_comparison.py**
* upgraded to point to 4.0 api
* changed references to spaces endpoints to folders endpoints
* transport_options was breaking the script even in 3.1 -- applied changes based on [Eric's recommendation here](https://community.looker.com/looker-api-77/setting-a-timeout-parameter-for-the-run-look-function-with-the-sdk-28410)
**examples/python/create_db_connections.py**
* upgraded to point to 4.0 api
**examples/python/disable_users_by_email.py**
* upgraded to point to 4.0 api
**examples/python/download_tile.py**
* upgraded to point to 4.0 api
* transport_options was breaking the script even in 3.1 -- applied changes based on [Eric's recommendation here](https://community.looker.com/looker-api-77/setting-a-timeout-parameter-for-the-run-look-fun …
=> chore: upgrade python examples to api 4.0 + bug fixes

packages/sdk-codegen-scripts/scripts/specLinter.ts, packages/sdk-codegen/src/specDiff.ts
- fix broken csv formatting
- auto update specs to OpenAPI format
- show settings used for run
=> chore: spec linter improvements

packages/api-explorer/e2e/MethodScene.spec.ts, packages/api-explorer/e2e/diffScene.spec.ts, packages/api-explorer/e2e/e2e.spec.ts, packages/api-explorer/src/components/SideNav/SideNavMethods.spec.tsx, packages/api-explorer/src/components/SideNav/SideNavMethods.tsx, packages/api-explorer/src/routes/AppRouter.tsx, packages/api-explorer/src/scenes/ErrorDetailScene/ErrorDetailScene.tsx, packages/api-explorer/src/scenes/ErrorDetailScene/index.ts, packages/api-explorer/src/scenes/MethodScene/MethodScene.tsx, packages/api-explorer/src/scenes/MethodScene/components/DocResponses/DocResponseTypes.tsx, packages/api-explorer/src/scenes/MethodScene/components/DocResponses/DocResponses.spec.tsx, packages/api-explorer/src/scenes/MethodScene/components/DocResponses/DocResponses.tsx, packages/api-explorer/src/scenes/index.ts, packages/api-explorer/src/utils/hooks/index.ts, packages/api-explorer/src/utils/hooks/navigation.spec.ts, packages/api-explorer/src/utils/hooks/navigation.ts, packages/api-explorer/src/utils/hooks/useQuery.ts, packages/code-editor/src/Markdown/common.tsx, packages/extension-utils/src/APIErrorDisplay/APIErrorDisplay.spec.tsx, packages/extension-utils/src/APIErrorDisplay/index.ts
Navigating to `/:specKey/err/:errorCode/:verb/*` will redirect users to the correct method scene with an error query param containing the error code. 
To test, navigate to `/4.0/err/400/get/content_metadata/:content_metadata_id`. This change will:
- automatically redirect users to the correct method scene (`h/4.0/methods/Content/content_metadata?e=400` based on the example above)
- scroll the `Responses` section into view
- automatically select the tab based on the error code in the url 
- fetch and render detailed error markdown
=> feat: error documentation redirect and support for detailed error content

.github/workflows/python-ci.yml
disable python integ tests on 22.12, 22.14 and 22.16
=> chore: disable python integ tests on 22.12, 22.14 and 22.16

packages/api-explorer/src/components/DocMethodSummary/DocSummaryStatus.spec.tsx, packages/api-explorer/src/components/DocStatus/DocStatus.spec.tsx
Some tests that check beta status broke because the methods were no longer beta
We'll need to snapshot the specs or mock them in the future to avoid this breaking again
=> chore: fix API Explorer tests

packages/api-explorer/src/components/DocMethodSummary/utils.spec.tsx, packages/api-explorer/src/components/DocMethodSummary/utils.tsx, packages/run-it/src/components/MethodBadge/MethodBadge.tsx, release-please-config.json
Tooltip, text color, and tests are updated for alpha endpoints
- also removed forced CalVer in release-please-config.json
APIX end to end tests are failing but that's not caused by anything I changed
=> chore: add APIX badge support for alpha endpoints

package.json, packages/api-explorer/src/components/SelectorContainer/SdkLanguageSelector.tsx, packages/api-explorer/src/scenes/MethodScene/MethodScene.tsx, packages/api-explorer/src/scenes/MethodTagScene/MethodTagScene.spec.tsx, packages/api-explorer/src/scenes/MethodTagScene/MethodTagScene.tsx, packages/api-explorer/src/scenes/TypeTagScene/TypeTagScene.spec.tsx, packages/api-explorer/src/scenes/TypeTagScene/TypeTagScene.tsx, packages/sdk-codegen/src/typescript.gen.spec.ts, packages/sdk-codegen/src/typescript.gen.ts, yarn.lock
- sdk selection was broken on the developer portal, because some scenes weren't using the react dom `location` for `location.pathname`, which caused the path to include `/api/explorer` when it shouldn't have
- This also fixes a crash bug when clicking on a method summary page from a type summary page
- also introduces **funSDK** syntax into the TypeScript `makeTheCall()` that now shows in RunIt
- also updates yarn-deduplicate
=> fix: various path navigation issues

go/integration/integration_test.go, go/rtl/auth.go
Changes copied from **approved** PR from forked repo https://github.com/looker-open-source/sdk-codegen/pull/1074
Original commit message: 
I added status code handling in the Go SDK to deal with delete endpoints' response body.
In Looker API, delete endpoints call returns empty response body with status code 204 when the API call is succeeded.
Such API call will be failed with EOF error in the current implementation because of reading empty response body.
=> fix: Handle Go SDK 204 no responses correctly

packages/sdk-codegen/src/sdkModels.spec.ts
=> fix: spec parsing unit tests

packages/hackathon/artifact.ipynb, packages/hackathon/src/models/Hackathons.ts, packages/hackathon/src/models/Judgings.ts, packages/hackathon/src/models/Projects.ts, packages/hackathon/src/models/Registrations.ts, packages/hackathon/src/models/TeamMembers.ts, packages/hackathon/src/models/Technologies.ts, packages/hackathon/src/models/Users.ts, packages/wholly-artifact/src/RowModel.ts
WhollyArtifact's RowModel derives it's tablename from the name of the constructor `constructor.name`. Turns out a constructor's name is generated by minified code, so that's a no go. Found out about this while migrating our hack.looker.com hack app, since it requires bundled/minified js. 
- Updated WhollyArtifact package to remove Rowmodel's tablename implementation
- Updated hack app to specify tablename for each RowModel.
- Also updated artifact notebook for convenience.
=> fix: WhollyArtifact/Hack App table name fix

kotlin/src/main/com/looker/rtl/ErrorDoc.kt, kotlin/src/main/com/looker/rtl/Transport.kt, kotlin/src/test/TestErrorDoc.kt, packages/sdk-rtl/src/errorDoc.spec.ts, packages/sdk-rtl/src/errorDoc.ts
ErrorDoc implementations support both docs.looker.com and cloud.google.com redirect host patterns
=> chore: support new cloud redirect host

packages/hackathon/artifact.ipynb, packages/hackathon/src/Hackathon.tsx, packages/hackathon/src/data/common/reducer.ts, packages/hackathon/src/data/projects/sagas.ts, packages/hackathon/src/data/sheets_client.ts, packages/hackathon/src/models/Projects.ts, packages/hackathon/src/scenes/JudgingScene/JudgingScene.tsx, packages/hackathon/src/scenes/ProjectsScene/ProjectsScene.tsx, packages/hackathon/src/scenes/ProjectsScene/components/ProjectList.tsx, packages/hackathon/src/scenes/ProjectsScene/components/ProjectView.tsx, packages/hackathon/src/scenes/ResourceScene/ResourceScene.tsx, packages/hackathon/src/scenes/ResourceScene/resource_data.ts
- Fixed race condition where project members was being simultaneously create/deleted and fetched. This lead to member count in frontend being incorrect. Updated loading spinner logic to correctly stop spinning after project members have been created/deleted and then fetched. 
- Updated resources page to use multi select and also filter on both type and domain for nicer/sleeker UX.
- Updated resources page's card's font to be smaller and also added one more column.
- Update project/judging list to have UI that points out the options/actions. 
- Updated the message bar to always be floatin on top, instead of at top of page. Ltos of times when you do an actions you dont see the result message because you have to scroll up. This makes a confusing UX, so always have the message bar float at …
=> fix: Multiple hack app fixes and changes

packages/hackathon/src/data/add_user/sagas.ts
Turns out API will return empty array instead of null/undefined defined in the type.
=> fix: Fix admin add user to correctly generate API3 keys.

packages/extension-api-explorer/package.json, packages/hackathon/src/authToken/extensionProxyTransport.ts, packages/run-it/src/components/ResponseExplorer/ResponseExplorer.spec.tsx, packages/run-it/src/components/ResponseExplorer/ResponseExplorer.tsx, packages/run-it/src/test-data/responses.ts, packages/sdk-node/src/nodeTransport.spec.ts, packages/sdk-node/src/nodeTransport.ts, packages/sdk-rtl/src/browserTransport.spec.ts, packages/sdk-rtl/src/browserTransport.ts, packages/sdk-rtl/src/paging.spec.ts, packages/sdk-rtl/src/transport.ts, release-please-config.json
The TypeScript SDKs have two new properties for tracking the "raw" request time:
- `requestStarted` timestamp right before the request begins
- `responseCompleted` timestamp right after the response is downloaded, and before the payload is parsed (in most cases)
API Explorer will also display the elapsed time in seconds for API requests on the RunIt response tab now
=> feat: add request time tracking

packages/extension-sdk/package.json, packages/extension-sdk/src/connect/extension_host_api.spec.ts, packages/extension-sdk/src/connect/extension_host_api.ts, yarn.lock
Fixes an issue with OAUTH calls whereby the call initially fail because the chatty timeout (30 seconds) is exceeded.
The fix is to rely on the new AbortController signal feature added to chatty. When a signal is provided, chatty does not timeout and instead relies on signal abort to cancel the call. For OAUTH a signal is provided which bypasses the timeout. The abort is never called but this does not matter as the OAUTH processing monitors the OAUTH child window and knows when a user has terminated the flow in a manner other than a successful login.
=> fix: oauth timeout

packages/run-it/src/components/ResponseExplorer/ResponseExplorer.tsx
Don't display time if timestamps are missing
=> chore: request time display cleanup

packages/run-it/src/utils/requestUtils.ts
This way we still get a reasonable timing metric from the API request in the RunIt response explorer
=> feat: track request time if the transport doesn't

packages/api-explorer/src/scenes/HomeScene/HomeScene.tsx
Updates the API Explorer home page to show the Looker release version that produced the specification being viewed, if the `x-looker-release-version` tag is present in the `info` section of the spec
=> feat: show Looker release version providing API specification

packages/run-it/src/components/RequestForm/formUtils.spec.tsx, packages/run-it/src/components/RequestForm/formUtils.tsx
explains that `false` boolean properties must be removed from JSON body requests for API Explorer if they shouldn't be passed to the API call
=> chore: improve body hint for RunIt request form

.github/workflows/release-please.yml
Our old release please version is now blocked because it was node 12. This updates it to the new version.
=> chore: update release please

packages/sdk/README.md
This is a change to the sdk readme. Since we link the versions of all our calendar versioned packages, this change plus the below "Release-As" git commit body footer will tell release-please to set all calendar versions packages to 23.0.0.
Release-As: 23.0.0
=> chore: Update sdk Readme and kickoff Release 23.0.0

yarn.lock
yarn.lock on main doesn't match the yarn.lock from `bin/rebuild`
=> chore: update yarn.lock for repeatability

release-please-config.json
extension-playground's package.json is set to:
```
"@looker/extension-sdk": "^22.4.2",
"@looker/extension-sdk-react": "^22.4.2",
"@looker/sdk": "^22.4.2",
```
We need release-please to update it's package.json or else what happens is right now, on calling `yarn`, we download the pinned versions and they are added to our lock file since the latest calendar version is 23.0.0 which doesn't work with the caret `^` that pins to the 22 major version. This probably pulls in the old build issue. I'm hoping this fixes that. 
This change will also release extension-playground as 1.0.0.
=> chore: Release extension-playground

yarn.lock
yarn dedupe:ci check only happens on apix ci, tssdk ci and lerna publish workflows. It wasn't triggered in my previous change which only changed extension-playground, but was triggered in the release-please pr branch. So deduping.
=> chore: Dedupe yarn.lock

.github/workflows/p3-issue-label.yml, .github/workflows/triage-issue-label.yml
New issues get "p3" and "need triage". Reopened issues get "p3". Went with simpler approach of 2 workflows instead of figuring out how to do branching logic in a workflow.
=> chore: Added workflows to label new/reopened issues

packages/wholly-artifact/src/WhollyArtifact.ts
Using purely functional SDK now. Oversight from before.
=> chore: clean up WhollyArtifact construction

packages/extension-utils/src/OAuthConfigForm/OAuthConfigForm.tsx
This PR fixes the OauthConfigForm's help message. This work was highlighted in https://github.com/looker-open-source/sdk-codegen/pull/1280
=> Fix: Oauth message on failed verify

go/rtl/auth.go, go/rtl/auth_test.go
Implement `AgentTag` defined in settings and set Go SDK's outgoing `Do` requests with the User-Agent header. 
Fixes issue: https://github.com/looker-open-source/sdk-codegen/issues/1274
=> fix: Set Go SDK's User-Agent header

go/rtl/auth.go, go/rtl/auth_test.go
Implement the Timeout field in our config/settings. Make use of request context to control timeout.  Timeout defaults to 120 seconds. Hopefully the unit tests are not flaky with the new timeout tests.
Fixes https://github.com/looker-open-source/sdk-codegen/issues/692
=> fix: Implement Go SDK timeout

packages/embed-components/src/QuickEmbed/QuickEmbed.spec.tsx, packages/embed-components/src/QuickEmbed/QuickEmbed.tsx, packages/embed-components/src/QuickEmbed/index.ts, packages/embed-components/src/Theme/SelectTheme.spec.tsx, packages/embed-components/src/Theme/SelectTheme.tsx, packages/embed-components/src/Theme/state/sagas.spec.ts, packages/embed-components/src/Theme/state/sagas.ts, packages/embed-components/src/Theme/state/slice.ts, packages/embed-playground/package.json, packages/embed-playground/src/EmbedPlayground.tsx, packages/embed-playground/src/StandaloneEmbedPlayground.tsx, packages/embed-playground/src/index.tsx, packages/embed-services/src/EmbedUrl.ts, packages/embed-services/src/ItemList.spec.ts, packages/embed-services/src/ItemList.ts, packages/embed-services/src/ThemeService.spec.ts, packages/embed-services/src/ThemeService.ts, yarn.lock
To test:
1. run `yarn && yarn build`
2. navigate to `packages/embed-playground`
3. run `yarn play`
4. In your browser, visit `https://localhost:8080/dashboards/42` or `https://localhost:8080/explore/thelook/orders` or `https://localhost:8080/looks/42` and authenticate.
5. Play around with having different existing url params (including `theme`)
=> feat: QuickEmbed component

packages/embed-components/src/QuickEmbed/QuickEmbed.spec.tsx, packages/embed-components/src/QuickEmbed/QuickEmbed.tsx
Adding onCopy function to QuickEmbed component and added tests for both close and copy. 
document.execCommand = jest.fn(), was added to the test file because the copying to clipboard function must be mocked.
=> Add onCopy prop for QuickEmbed

packages/extension-api-explorer/README.md, packages/extension-api-explorer/bin/deploy, packages/extension-api-explorer/manifest.lkml
updated the deployment script to keep the deployed `manifest.lkml` current
=> chore: update APIX extension deployment

kotlin/build.gradle, kotlin/src/main/com/looker/sdk/ApiSettings.kt
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally, it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)
Fixes #1386 🦕
=> Replace ini4j with apache-commons-configuration

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/hackathon-ci.yml, .github/workflows/required-checks-hack-ci.yml, .github/workflows/tssdk-ci.yml, package.json, yarn.lock
Resolve https://github.com/looker-open-source/sdk-codegen/security/dependabot/59
=> chore: resolve critical dependabot notice on parse-url

packages/extension-sdk/src/connect/tile/tile_sdk.spec.ts, packages/extension-sdk/src/connect/tile/tile_sdk.ts, packages/extension-sdk/src/connect/tile/types.ts, packages/extension-sdk/src/connect/types.ts, packages/extension-sdk/src/connect/visualization/types.ts, packages/extension-sdk/src/connect/visualization/visualization_sdk.ts, packages/extension-tile-playground/src/components/Inspector/components/EventTester/EventTester.tsx, packages/extension-tile-playground/src/components/Inspector/components/TileHostData/TileHostData.tsx, packages/extension-tile-playground/src/components/VisualizationTile/VisualizationTile.tsx
feat: Add updating row limit and remove trigger from extension SDK
With the addition of being able to update the row limit with a separate event here, there is no longer a need to have the trigger functionality copied from Custom Visualizations as all trigger types are covered by the existing SDK methods. 
Also some minor updates to the example extension just for testing purposes for the reviewer of this PR.
=> Add update row limit in extension

kotlin/src/main/com/looker/rtl/Transport.kt
CLONE OF https://github.com/looker-open-source/sdk-codegen/pull/1420
This small fix to the Kotlin Transport code, disables automatic User Agent suffixing by the Google-HTTP-Java library.
Looker is very specific about User Agent names, especially when using cookieless embedding sessions and this change will fix the contract violation between this code and the API.
Related to this [discussion](https://github.com/looker-open-source/sdk-codegen/commit/5407e6316491fc2ed6fcc017b317d931c283179c#commitcomment-136501445).
=> fix(Transport): Disable automatic User Agent Suffix [clone of #1420]

.release-please-manifest.json, packages/extension-tile-playground/package.json
extension-tile-playground package was not part of the release-please manifest. This meant release-please does not update its package.json with every release PR. 
For context:
Our release PR branch was failing on build. Why?
1. `extension-tile-playground` depends on `extension-sdk`. `extension-sdk` was on 23.20.1. 
2. We added a breaking change to it and had to update `extension-tile-playground`. All done in 1 PR.
3. Latest main branch built successfully since since the playground is pointing to `extension-sdk` 23.20.1 which is latest in repo. 
4. However release-please created a release PR that bumped `extension-sdk` to 24.0.0, BUT did not bump `extension-tile-playground` package.json's `extension-sdk` dependency which stayed on 23.20.1
5. This forced yarn to pull in `extension-sdk` …
=> chore: Add extension-tile-playground package to release-please manifest

release-please-config.json
Missed one line change to properly release new package. For context read previous commit: https://github.com/looker-open-source/sdk-codegen/commit/fbec58f290a31cc55b8ea96de28f366810b532a9
=> chore: Add extension-tile-playground package to release please config

bin/sdk_gen
- Removed smoke tests as our CI already runs them. 
- Added python and kotlin linting to the script
- Added `yarn fix` to the script. For some reason, our pre-commit hook hangs on eslint. So if we first fix the eslint issues with `yarn fix` this lets our pre-commit hook work. 
Additionally:
- Updated our playbook with additional setup steps for linting
- Updated our playbook and console output with smoke test debugging steps if CI breaks
Confirmed it generates sdk with consistent styling. From last generation:
`26 files changed, 519 insertions(+), 188 deletions(-)`
=> chore: Update sdk_gen script to lint and not do smoke tests

.github/workflows/lerna-publish.yml
Our publishing workflow was unable to execute `lerna publish` to publish our npm packages because its method of execution `npm bin` is not supported anymore. This stackoverflow article for more context: https://stackoverflow.com/questions/9679932/how-to-use-executables-from-a-package-installed-locally-in-node-modules
- Switching to using `npx`. I confirmed locally that `npx lerna -h` works which means other lerna commands should work. (unable to do publishing dry run because our version of lerna is too old, and doesn't have that option)
=> chore: Fix NPM publishing workflow

package.json
Since we're now on node 18 in our CI and dependencies.
=> chore: Update node version to 18 in package.json

python/looker_sdk/error.py, python/looker_sdk/rtl/api_methods.py
Lookups now take place against the CDN to find a more detailed error guide. The url to that error guide, and the error guide itself - a markdown document - are included in the SDKError class and the ErrorDetail class.
=> feat: error-doc handling in python SDK

python/looker_sdk/error.py
fix for https://github.com/looker-open-source/sdk-codegen/issues/1460
=> fix: backslash in regex causing warnings - switch to raw string

python/Pipfile
As stated in issue #1410 , `cattrs` appears to have introduced a breaking change starting in version 23.2.
Fixes #1468
=> fix(deps): limit cattrs to versions <23.2

packages/extension-api-explorer/manifest.lkml
Allow https://cloud.google.com as an external URL for the API Explorer extension
=> fix: allow cloud.google.com for the API Explorer extension

packages/sdk-codegen/src/go.gen.ts
This change alters the Go SDK client struct to accept an interface instead of the AuthSession. The interface allows for custom implementations of the RTL package, but since the existing AuthSession fulfills the new interface (its based on the Do method from the current AuthSession after all) this change will be completely transparent to those who are currently using the current AuthSession.
=> feat: update Go SDK to accept auth session interface

.github/workflows/tssdk-ci.yml, packages/sdk-node/README.md, packages/sdk/README.md, shell.nix
Allow Node 20 as a runtime environment for the Looker TypeScript SDK
=> feat: allow node 20 for the TS SDK

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/hackathon-ci.yml, .github/workflows/python-ci.yml, .github/workflows/required-checks-hack-ci.yml, .github/workflows/tssdk-ci.yml, yarn.lock
Copy of https://github.com/looker-open-source/sdk-codegen/pull/1517
=> chore(deps): Bump express from 4.18.2 to 4.21.1

package.json, yarn.lock
Copy of https://github.com/looker-open-source/sdk-codegen/pull/1524
Bumps [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) from 2.0.6 to 2.0.7.
- [Release notes](https://github.com/chimurai/http-proxy-middleware/releases)
- [Changelog](https://github.com/chimurai/http-proxy-middleware/blob/v2.0.7/CHANGELOG.md)
- [Commits](https://github.com/chimurai/http-proxy-middleware/compare/v2.0.6...v2.0.7)
---
updated-dependencies:
- dependency-name: http-proxy-middleware dependency-type: indirect ...
=> chore(deps): Bump http-proxy-middleware from 2.0.6 to 2.0.7

examples/python/update_explores_in_dashboards.py
Currently, there is no example on how to update explores in dashboards. There are some list of steps given [here](https://cloud.google.com/looker/docs/best-practices/how-to-change-the-model-or-explore-of-a-look#h_01EPFP7F2B58J803QDZNZBX2G9) but having an actual example could enable Looker Admins or developers to implement this quickly. Also, this could serve as a basis for using the API to update dashboards
Fixes #1372
=> Create example script for updating explores in dashboards

kotlin/src/main/com/looker/rtl/Transport.kt
- Provide HTTP request and response details on SDKErrorResponse.
- Provide the cause of SDKError for chaining and re-throwing
- Add LookerApiException, which includes the same request/response information as SDKErrorResponse.
- Mark ok() as Deprecated, because it throws java.lang.Error, which is not something application code should do.
- Add SDKResponse::getOrThrow() instance method, patterned after Kotlin's built-in Result type, which handles SDKErrorResponse by throwing the newly introduced LookerApiException
- …
=> Improve error handling in Transport.kt

.github/workflows/kotlin-ci.yml, kotlin/src/main/com/looker/rtl/AuthSession.kt, kotlin/src/main/com/looker/rtl/Transport.kt
I'm hesitant to change this function too much, since we don't know what kind of odd dependencies on its current behavior might exist. However, adding exception chaining and surfacing the original error message seems like a risk worth taking.
- Eliminate duplicated version in AuthSession by delegating to a shared implementation defined on the SDKResponse companion object.
- For the SDKError case:
- Set Error.message from SDKError.message
- Set Error.casue from SDKError.cause
- Also ran `ktlint -F` on the files I changed so that `gradle check` would pass the linting stage
- Also added kotlin-ci.yml to run `./gradlew jar` on kotlin changes
Fixes #1539 🦕
=> fix: Improve ok() helper function

.github/workflows/apix-ci.yml, .github/workflows/codegen-ci.yml, .github/workflows/go-ci.yml, .github/workflows/python-ci.yml, .github/workflows/tssdk-ci.yml, packages/api-explorer/package.json, packages/code-editor/package.json, packages/embed-components/package.json, packages/embed-playground/package.json, packages/extension-api-explorer/package.json, packages/extension-playground/package.json, packages/extension-tile-playground/package.json, packages/extension-utils/package.json, packages/hackathon/package.json, packages/run-it/package.json, yarn.lock
The `@looker/components` and `@looker/design-tokens` packages were out of date. This updates them to the latest.
=> fix: update looker TypeScript package dependencies

kotlin/src/test/TestMethods.kt
https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/Folder/all_folders was changed in the last 6 months to return `FolderBase` instead of `Folder`
Updating test to reflect API change.
Fixes #1567  🦕
=> fix(testAllFolders): Updated Kotlin test after API change for all_folders

.github/workflows/go-ci.yml, go/example/main.go
=> Fix: fixed bug in go example
